### ISSUE TITLE
Don't generate HTML by default

### ISSUE THREAD

**Issue by awinogradov** [posthtml/posthtml#102]
Posthtml generate HTML now after processing a string with markup. In special situations this functionality isn't required. If you want to get tree only HTML generation decrease your performance. 

How to: html is method of posthtml-tree instead of attribute. Ex: `posthtml().process(String).html()`.

**Comment by kisenka** [comment]
BTW what about rename this method to `toString`? Because sometimes result is XML

**Comment by zxqfox** [comment]
`Object.define(processResult, 'html', function() { ... })` ? Btw, we could also provide toString as a synonyme.

**Comment by awinogradov** [comment]
`toString` is't correct :( For ex I want to generate function from `posthtml-tree`. Main idea is generation result when you need it. Because we have several examples of usage posthtml in different services and html generating is making communication process slowly.

**Comment by voischev** [comment]
look at https://github.com/posthtml/posthtml/issues/101#issuecomment-177917921

**Comment by voischev** [comment]
close #133
