### ISSUE TITLE
`isPromise` check fails in any environment without Promise

### ISSUE THREAD

**Issue by terinjokes** [posthtml/posthtml#105]
Trying to avoid Promises by setting option `{sync: true}` still results in a check that the returned value isn't a Promise.

**Comment by zxqfox** [comment]
Hah, nice catch!

**Comment by terinjokes** [comment]
@zxqfox CI caught it testing the active LTS releases + current stable.

**Comment by voischev** [comment]
@terinjokes require('es6-promise').polyfill(); as a solution to the problem?

**Comment by voischev** [comment]
@terinjokes 
plz check this in your env 

<img width="367" alt="screen shot 2016-02-05 at 14 12 02" src="https://cloud.githubusercontent.com/assets/1510217/12844794/c03a783a-cc12-11e5-9e7e-15d45cd58770.png">

https://travis-ci.org/posthtml/posthtml/builds/107209773
commit https://github.com/posthtml/posthtml/commit/d0a53412519a145801b9e3ccf02fed070f2c5b72

**Comment by voischev** [comment]
https://travis-ci.org/posthtml/posthtml/builds/107218333

**Comment by terinjokes** [comment]
@voischev: the solution is to check that Promise is in the global object before doing an instanceof check, or follow what the `is-promise` module does skip the instanceof check entirely.

**Comment by voischev** [comment]
@terinjokes your nodejs version?

**Comment by terinjokes** [comment]
0.10, an LTS release in maintaince mode.

**Comment by voischev** [comment]
@terinjokes https://travis-ci.org/posthtml/posthtml/builds/107311211
 fixed in https://github.com/posthtml/posthtml/commit/fdc2b72e9108a8698853e720b57750276a76e270
Thanks a lot! :)

**Comment by terinjokes** [comment]
@voischev thanks :+1:. looking forward to a release.

**Comment by voischev** [comment]
@terinjokes released v0.8.2
