### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by voischev** [posthtml/posthtml#11]

**Comment by verybigman** [comment]
:+1:

**Comment by voischev** [comment]
@squorax ideas? ;)

**Comment by TrySound** [comment]
![posthtml](https://cloud.githubusercontent.com/assets/5635476/8927905/70410668-3523-11e5-800a-3c2dc83ac86b.png)

**Comment by voischev** [comment]
@TrySound ha-ha! Fun! 
More? :)

**Comment by TrySound** [comment]
![posthtml](https://cloud.githubusercontent.com/assets/5635476/8929487/86810e86-352e-11e5-962c-88b26ba58093.png)

**Comment by TrySound** [comment]
![posthtml2](https://cloud.githubusercontent.com/assets/5635476/8929789/938a82b8-3530-11e5-8cff-6597b6928be4.png)

**Comment by voischev** [comment]
No no no, it's like Grunt!)

**Comment by TrySound** [comment]
Wolf is not boar

![posthtml2](https://cloud.githubusercontent.com/assets/5635476/8930765/36b629e4-3539-11e5-86a4-0e23d2b89e16.png)

**Comment by VovanR** [comment]
![screenshot_2015-07-28_15-00-30](https://cloud.githubusercontent.com/assets/430003/8930860/38f11e2a-353a-11e5-9938-7f9422e77a9c.png)

**Comment by TrySound** [comment]
Mu-ha-ha! Hey, Johnny!

![posthtml2_joker](https://cloud.githubusercontent.com/assets/5635476/8930865/426e006c-353a-11e5-911a-11a32a374c6a.png)

**Comment by TrySound** [comment]
> Achtung!

![posthtml2_hitler](https://cloud.githubusercontent.com/assets/5635476/8930915/db0501ea-353a-11e5-9c45-3a0a90039286.png)

**Comment by VovanR** [comment]
He looks sad :disappointed:

**Comment by TrySound** [comment]
> Achtung?

![posthtml2_hitler](https://cloud.githubusercontent.com/assets/5635476/8931065/418f410e-353c-11e5-8b41-b79fd116ef3e.png)

**Comment by TrySound** [comment]
![posthtml_man](https://cloud.githubusercontent.com/assets/5635476/8931258/7ddda488-353d-11e5-97dc-1821503495e5.png)

**Comment by VovanR** [comment]
![html5_logo_and_wordmark](https://cloud.githubusercontent.com/assets/430003/8931612/392aee7e-3540-11e5-8f0b-a113c3767a85.png)

**Comment by voischev** [comment]
@VovanR nice try!!!

**Comment by VovanR** [comment]
We need designers =)

**Comment by TrySound** [comment]
We need brains! More brains!

![Brains!](http://u.kanobu.ru/images/2010/07/01//6d361097-9d1d-4cc9-ad0b-1bdfa744ef51.jpg)

**Comment by VovanR** [comment]
Mm. Zombie's head as logo? :skull: Nice

**Comment by 7immy** [comment]
Any good?
![](https://lh3.googleusercontent.com/uX6htyG_jmpiYp7UTdCQaZxiTvbVI4mckzDk23PrB0Ms-l5hkwbR4Vp_W5yI1-xq5o6uk40dFmOrwFI=w1301-h807-rw)

**Comment by TrySound** [comment]
Looks like polymer :)

**Comment by verybigman** [comment]
I like first!

**Comment by 7immy** [comment]
Ha so it does

**Comment by TrySound** [comment]
First looks like Umbrella's DNA :))

**Comment by verybigman** [comment]
Also square in one color is good to)

**Comment by VovanR** [comment]
First looks like raccoon. Maybe draw raccoon, styled as Grunt, Bower etc.?

**Comment by VovanR** [comment]
[Nice](http://www.google.ru/imgres?imgurl=http://www.walkingmountains.org/wp-content/uploads/2015/04/Raccoon-1.jpg&imgrefurl=http://www.walkingmountains.org/2015/04/cute-little-bandits/&h=990&w=1188&tbnid=CPGOhvzQd6oMDM:&tbnh=166&tbnw=200&usg=__2eM6iGmh-SJmSecZgFyYFmc_w2Y=&docid=EHkeXhkHgW2XTM&itg=1)

**Comment by Grawl** [comment]
<post>

**Comment by Grawl** [comment]
`<post>`

**Comment by VovanR** [comment]
`</post>`
Because **post** :smile:

**Comment by 7immy** [comment]
![](https://drive.google.com/a/isbell.net/uc?export=view&id=0B06gk7uOoLmiLVdEMGI3dlhaNG8)
If anyone wants a bigger version of one of these let me know :)

**Comment by voischev** [comment]
Wow! Nice! %) Ok!
@7immy We may use your ideas in future trying?

**Comment by zxqfox** [comment]
@7immy Nicely done ;-)

I like `<POST>` and the font you using. But not sure about colouring. Guess `<P>` or `</>` could be fine as square variant.

**Comment by zxqfox** [comment]
`PH` feels like pharmacy or about... ;-)

**Comment by verybigman** [comment]
@7immy i want this in big size. We set it as our logo in first time.

<img width="192" alt="screen shot 2015-07-31 at 10 34 05" src="https://cloud.githubusercontent.com/assets/982072/9002678/ce6dfe96-376f-11e5-832f-6e03684fd051.png">

**Comment by Grawl** [comment]
I like last of @7immy. Just `<post>` as I suggested.

Also we can use `</html>`.

**Comment by voischev** [comment]
`<post>` http request? (

**Comment by voischev** [comment]
@7immy Maybe more details? 
![](https://cloud.githubusercontent.com/assets/982072/9002678/ce6dfe96-376f-11e5-832f-6e03684fd051.png)

Look At DNA / DNA mutation

![amazing_arabesque](https://cloud.githubusercontent.com/assets/1510217/9002972/743f968e-3772-11e5-913a-6a923d74daa8.jpg)
![0_933fe_7bbd55a9_xl](https://cloud.githubusercontent.com/assets/1510217/9002974/746881e8-3772-11e5-9db1-42c9c9531365.jpeg)
![gene-mutation schema](https://cloud.githubusercontent.com/assets/1510217/9002973/746875f4-3772-11e5-86b9-14eba66adb0a.jpg)

**Comment by verybigman** [comment]
In small icons is bad
<img width="49" alt="screen shot 2015-07-31 at 14 40 41" src="https://cloud.githubusercontent.com/assets/982072/9006618/33b6e1f6-3792-11e5-9648-bd498043edd2.png">

**Comment by voischev** [comment]
:(

**Comment by zxqfox** [comment]
That's why I like `</>`

**Comment by Grawl** [comment]
Maybe we can get some ideas from Autoprefixer? It uses [Philosopher's stone](http://www.wikiwand.com/en/Philosopher%27s_stone) as logo and it's pretty awesome. [In releases](https://github.com/postcss/autoprefixer/releases) it uses other alchemical symbols. It's a good way to go I think.

Is CSS is philosophy then HTML is a structure. PostHTML is a new era of structurizing a things? It's a space of stars and planets we will transform. I think [astronomy](http://www.wikiwand.com/en/Astronomy).

Also I just found Wotans Knot that will be good for PostHTML too:

![valknut-wotans-knot-celtic-endless-knot-15411587](https://cloud.githubusercontent.com/assets/846774/9021187/a6492c40-3870-11e5-8092-2c6dc6ed5912.png)

Of course we need just middle part without circle.

Also there is a large version with twisted forms:

![shutterstock_132284090](https://cloud.githubusercontent.com/assets/846774/9021191/dcbae0e8-3870-11e5-853e-ac6d4bdb2e32.jpg)

**Comment by voischev** [comment]
@Grawl Good idea!

**Comment by awinogradov** [comment]
:+1:

**Comment by 7immy** [comment]
Sorry guys, I'm a bit busy atm. I'll get to this when I can but it maybe a little while.

In the mean time..

**Small icons**
I think @awinogradov makes a good point about small icons. That logo wasn't meant for small sizes and would require adjustment to fit that size. This would be the case for any logo. For the current chosen logo I think `</ >` would be a good idea however I'm not sure this shouts 'PostHTML' enough.

**DNA Option**
I'll try and develop the DNA option further. @Grawl makes a good point about HTML re-structuring and I think DNA is a good analogy. @voischev, lack of detail is good in a logo these days - think clean, clear, simple, rememberable. Perhaps you're really asking for the logo to have more context and character which is why you suggest DNA structuring?

**Wotan's Knot**
The knot is interesting. It maybe a bad idea to just copy the symbol but the pattern / illusion it creates is something that could be used as inspiration for something else.

**Comment by voischev** [comment]
@7immy "more details" about that :))
![posthtml](https://cloud.githubusercontent.com/assets/1510217/9113566/fcbe290e-3c5d-11e5-90de-3e62b340b751.png)

**Comment by 7immy** [comment]
Lol,  good point :) :+1:

**Comment by Grawl** [comment]
@7immy it's ok to just use that symbol. PostCSS did it already.

**Comment by voischev** [comment]
What do you say about this? Drafts
![cmtn8iluyai4wb3 jpg-large](https://cloud.githubusercontent.com/assets/1510217/9341200/1d6d9786-45fd-11e5-83d0-e9857ff802fa.jpeg)

**Comment by voischev** [comment]
![2015-09-20 13 46 36](https://cloud.githubusercontent.com/assets/1510217/9980349/1265fd0a-5f9e-11e5-9a68-3e2aba8ee46a.png)

**Comment by hudochenkov** [comment]
I'm sorry, this logo reminds me a sanitary napkin :(

**Comment by Grawl** [comment]
For me too.

**Comment by zxqfox** [comment]
Actually, it's good to hear, because posthtml as well as sanitary napkin is a special layer between two things. Great coincidence I'd say! ;-)

**Comment by voischev** [comment]
@zxqfox I think,  this is more — specific russian childhood ;)

**Comment by voischev** [comment]
Аnd yet. How to you such variant?
![cqd8kk-w8aam_mk](https://cloud.githubusercontent.com/assets/1510217/10174324/f90741b0-66f1-11e5-8fd8-92ae39581894.png)

**Comment by awinogradov** [comment]
Awesome changes!

**Comment by voischev** [comment]
Fixed
<img width="1432" alt="2015-09-30 10 22 46" src="https://cloud.githubusercontent.com/assets/1510217/10187399/f97788b6-6760-11e5-994c-b98fa5ab4059.png">

**Comment by voischev** [comment]
SVG File (rename .txt to .svg)
[PostHTML.txt](https://github.com/posthtml/posthtml/files/4989/PostHTML.txt)

**Comment by pepelsbey** [comment]
![octopus-html](https://cloud.githubusercontent.com/assets/105274/10191139/c77ef6da-6771-11e5-84d7-743e94ac25c0.png)

![sponge-html](https://cloud.githubusercontent.com/assets/105274/10191140/c7976f4e-6771-11e5-85b9-8fc78f57f55c.png)
