### ISSUE TITLE
Create PostHTML Wiki

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml#117]
I currently update the README and personally think it is quite a big bunch already on the way to become confusing. Separate wiki pages would give the different sections and usecases a better structure to find what people need and provide room for in-depth explanations e.g (write a plugin, middleware..). 

As i'm in the process already i would make a start, are there any concerns/arguments against creating a wiki?

**Comment by voischev** [comment]
Wiki sections nobody reads as experience shows. Now let's write in readme

I think about `docs/` folder like a PostCSS

**Comment by awinogradov** [comment]
:+1:

**Comment by michael-ciniawsky** [comment]
ok if you find the time would you pls take a look at [posthtml](https://github.com/michael-ciniawsky/posthtml) i made a wiki folder which can be renamed of course and the content structure is unfinished during the fact it's not my decision, e.g the content for writing a plugin and explanation of PostHTML internals (Tree, Class, you name it...) are splitted at the moment.

[posthtml-jade](https://github.com/michael-ciniawsky/posthtml-jade)
[posthtml-hapi](https://github.com/michael.ciniawsky/hapi-posthtml) released! :)

**Comment by awinogradov** [comment]
@michael-ciniawsky maybe PR?;)

**Comment by voischev** [comment]
`wiki/` rename to `docs/` and LGTM! Create PR

**Comment by michael-ciniawsky** [comment]
done can be closed
