### ISSUE TITLE
Create a website project repo which one can contribute to

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml#120]

**Comment by voischev** [comment]
site domain?
posthtml.io?

**Comment by michael-ciniawsky** [comment]
For getting started there is this option [JS DNS](http://dns.js.org/) name would be posthtml.js.org and free of charge, posthtml.io is good option since .org TLD is used by some nasty shit as it seems. Maybe posthtml.rocks? and split the Plugins Catalog like postcss does it with postcss.org and postcss.parts?

**Comment by voischev** [comment]
posthtml.js.org — good idea for start.

**Comment by voischev** [comment]
https://github.com/posthtml/posthtml-site

**Comment by michael-ciniawsky** [comment]
:+1:
