### ISSUE TITLE
Mistakes control

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml#121]
I'm working on CMS template and do not want to fix some “mistakes”:

### do not close unclosed tags

`header.src.html`

```html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
…
    <div class="wrapper">
```

No closing `</html>`,  `</body>` and `<div>` tags in this template. They are in `footer.src.html`.

Instead of proper partial, I have this:

`header.html`

```html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
…
    <div class="wrapper"></div>
</head>
</html>
```

### do not remove single closing tags

`footer.src.html`

```html
(some content)
    </div>
</body>
</html>
```

No opening `<html>`, `<body>` and `<div>` tags in this template. They are in `header.src.html`.

Instead of proper partial, I have this:

```html
(some content)
```

---

Is there a way to disable fixing this “mistakes”?

**Comment by voischev** [comment]
Tried to do like this?
```js
posthtml().process(header + footer)
```

**Comment by Grawl** [comment]
Here is my `templates.js` Gulp task:

```js
'use strict';
// global modules
var gulp = require('gulp');
var posthtml = require('gulp-posthtml');
var rename = require('gulp-regex-rename');
// own modules
var hat = require('./_hat.js');
// own data
var path = require('../path.json');
// public task: process source templates
gulp.task('templates', ()=> {
	var postcss = require('posthtml-postcss');
	var assets = require('postcss-assets');
	var postcssPlugins = [
		assets()
	];
	var processors = [
		postcss(postcssPlugins)
	];
	return gulp.src(path.srcTemplates)
		.pipe(hat())
		.pipe(posthtml(processors))
		.pipe(rename(/\.src.html$/, '.post.html'))
		.pipe(gulp.dest(path.srcTemplatesDir))
});
```

Where can I get `header + footer` for `process()`?

**Comment by zxqfox** [comment]
If you know that your partials are in header and footer, you can do: `gulp.src(headerAndFooter).pipe(concatWith(delimiter)).pipe(process).pipe(splitBy(delimiter)).pipe(gulp.dest())`

But if you have more complex structure this method won't work. You should combine and split them more carefully. At all, I don't see a good universal way to fit your needs with partial parsing and applying rules.

**Comment by Grawl** [comment]
So I need more control over PostHTML. Maybe like PostCSS.
Or I have to write some rules of concatenating into each folder with partials or so.

**Comment by voischev** [comment]
Like PostCSS? What is it like?

**Comment by Grawl** [comment]
Modular.

More clear example is [cssnano](http://cssnano.co). I can disable any part of minifier if it brokes my stylesheet or work too slow.

**Comment by voischev** [comment]
Hm... write example of which will process it in PostCSS

header.css
```css
.header-class {
    header-class-key1: val1;
```
footer.css
```css
    header-class-key2: val2;
}
```

**Comment by Grawl** [comment]
I think I'm understand you. PostHTML fix this mistakes in parsing time, right? And parser cannot return “broken” HTML, right?

**Comment by voischev** [comment]
Parser expects a valid html

**Comment by voischev** [comment]
@Grawl close issue?

**Comment by Grawl** [comment]
@voischev okay
