### ISSUE TITLE
Option to process selected subtrees instead of files

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml#131]
I think about solution for #121 some time and got this idea.

> Sometimes HTML parts is not a valid HTML – for example, `header.html` can contain `<div class="wrapper">` but closing tag for this `"wrapper"` is in `footer.html`

What if PostHTML allow you to select subtree to process just a small chunks of your HTML – for example, to process a CSS from `<style>` tag with `posthtml-postcss` plugin.

How it can be?

`gulpfile.js`

```js
var posthtml = require('gulp-posthtml');
var gulp = require('gulp');
gulp.task('posthtml', function () {
    var plugins = [
        …
    ];
    var options = {
        …
        selectiveProcessing: 'data-process-posthtml'
    };
    return gulp.src('./html/*.html')
        .pipe(posthtml(plugins, options))
        .pipe(gulp.dest('./dest'));
});
```

`header.html`

```html
<!DOCTYPE html>
<html>
<head>
  …
  <style data-process-posthtml>
    .class {
      display: flex; /* prefixes comes from posthtml-postcss */
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div block="blockname" data-process-posthtml>
      <!-- `block` and `elem` properties becomes classes with posthtml-bem -->
      <div elem="elemname">Element</div>
    </div>
```

`footer.html`

```html
  </div> <!-- wrapper -->
</body>
</html>
```

So PostHTML now will know what parts to process and do not generate `</div></body></html>` in `header.html`.

And we can allow users to define their own property or even a function to define parts to process. It maybe HTML comments like `<!-- posthtml-selective-processing: begin -->…<!-- posthtml-selective-processing: end -->`, specific CSS classes, other properties.

**Comment by voischev** [comment]
PostHTML doing too many changes over the tree. Comments will overlap

**Comment by michael-ciniawsky** [comment]
Simple prototype for posthtml-posthtml :D,  for plugins like posthtml-exp, posthtml-import etc. it might be useful when the import itself needs some posthtml transformations before the input happens. I need to do something similiar for the next posthtml-exp update in terms of partial loading but maybe there is a better solution on the horizont, how knows.... :)

## Setup
```js
'use strict'

const fs = require('fs')

const posthtml = require('posthtml')

// Plugins
const md = require('posthtml-md')
const bem = require('posthtml-bem')

const sub = require('../index')([
  {selector: 'test', plugins: [ bem() ]}, // subprocess 1
  {selector: 'test2', plugins: [ md() ]}  // subprocess 2
])

// HTML
let html = fs.readFileSync('./index.html', 'utf-8')

posthtml([ md(), sub ]) // main 
  .process(html)
  .then(result => {
    console.log(result.html)
    fs.writeFileSync('./result.html', result.html, 'utf8')
  })
```
## Plugin.prototype = {
```js
'use strict'

const parser = require('posthtml')
const render = require('posthtml-render')

exports = module.exports = function (options) {
  options = options || []

  return function PostHTMLSub (tree) {
    options.forEach(sub => {
      tree.match({tag: sub.selector}, node => {
        node.content = parser(sub.plugins)
          .process(render(node.content), {sync: true})
          .html
        return node
      })
    })
    return tree
  }
}
```
## }

## INPUT
```html
<!-- main -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>PostHTML</title>
</head>

<body>
  <p md>
    It knows *how* to work.
  </p>
  <test>
    <!-- subprocess 1 && main -->
    <div block="block">
      <div elem="element" md>It knows *how* to work.</div>
      <div elem="element" mods="mods" md>It knows *how* to work.</div>
    </div>
    <!-- end -->
  </test>
  <test2>
    <!-- subprocess 2 -->
    <p md>
      It knows *how* to work.
    </p>
    <p md>
      It knows *how* to work.
    </p>
    <!-- end -->
  </test2>
</body>
</html>
<!-- end -->
```
## RESULT
```html
<!-- main process -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>PostHTML</title>
</head>

<body>
  <p>It knows <em>how</em> to work.</p>

  <test>
    <!-- main &&/|| subprocess 1 -->
    <div class="block">
      <div class="block__element">
        <p>It knows <em>how</em> to work.</p>
      </div>
      <div class="block__element block__element_mods">
        <p>It knows <em>how</em> to work.</p>
      </div>
    </div>
   <!-- end -->
  </test>
  <test2>
    <!-- subprocess 2 -->
    <p>It knows <em>how</em> to work.</p>
    <p>It knows <em>how</em> to work.</p>
    <!-- end -->
  </test2>
</body>

</html>
<!-- end -->
```

**Comment by awinogradov** [comment]
@Grawl @michael-ciniawsky what status?

**Comment by michael-ciniawsky** [comment]
@awinogradov for what i sketched ealier there is now a plugin [posthtml-modules](https://github.com/canvaskisa/posthtml-modules) which processes html imports during the import(posthtml subprocess). (@canvaskisa made also a nice plugin for css modules, maybe ping him to add his plugins to the README).

imho the problem @Grawl issued, it's not possible to parse it with that document structure. posthtml(htmlparser2) don't recognizes the relations between different files, this needs either to be refactored or resolved on the 'file-level' e.g concat the files before processing them with posthtml. So for my part can be closed ;).

off-topic: I recently transfered my plugins to separate organizations I named posthtml-plugins (for posthtml) && posthtml-modules (posthtml for third parties e.g express-posthtml). Is there some interest in calling out to plugin creators to transfer their plugins/modules into the orgs for better support, bug fixes, up-to-date ensurance etc? Needs of course to be discussed how this would work in detail.

**Comment by awinogradov** [comment]
@michael-ciniawsky  why you don't want to store modules in posthtml org? We can get right access for you and others ;) I think the information in one place is more useful.

**Comment by michael-ciniawsky** [comment]
👍 that's what i meant :)  i just made this them to start some kind of organization, it must in no ways be there, but i believe it is better when some community effort is started to take care of the ecosystem as a hole as much as possible, instead of one, two, tree persons taking care of crucial parts alone. e.g i working on broccoli support (angular-cli, ember-cli) ,metalsmith support, yeoman plugin generator, jade like sugar syntax etc,  simply because there is room for doing that, but this shouldn't associated with me alone in terms of others maybe using those in production environments.

**Comment by awinogradov** [comment]
@michael-ciniawsky Ok) If we make the team of collaborators in posthtml org it will ok for you? ;)

**Comment by michael-ciniawsky** [comment]
sure invite me over to the org i transfer all my repos, make a first draft of how this would look like for others(greenkeeper, maintainer/creator section, collaborator section in README, ISSUE && PR Templates (.github), integrate to the plugins catalog on npm publish (prepublish) etc.). Then just express want your point of view is on a topic and we refactor disagreements.

**Comment by awinogradov** [comment]
@michael-ciniawsky you are welcome ;)

**Comment by michael-ciniawsky** [comment]
what are the minimum requirements to be accepted as collaborator for the org?

**Comment by awinogradov** [comment]
@michael-ciniawsky you should have the wish to be collaborator)

**Comment by michael-ciniawsky** [comment]
ok :) could you please consider to invite @GitScrum, he is the creator and current maintainer of posthtml-load-plugins and we also attempting to work on a linter based on posthtml

**Comment by awinogradov** [comment]
yes, sure! Can you explain linter's idea?

**Comment by GitScrum** [comment]
@michael-ciniawsky @awinogradov Thanks !

**Comment by michael-ciniawsky** [comment]
Sure  but it's early stages ;)

Resources for rules:

-[htmllint](https://github.com/htmllint/htmllint/wiki/Options)
-[htmlhint](https://github.com/yaniswang/HTMLHint/wiki/Rules)

e.g a posthtml-lint implementation for the 'title-no-dup' rule by [htmllint](https://github.com/htmllint/htmllint/wiki/Options#title-no-dup)

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Title 1</title>
    <title>Title 2</title>
  </head>
  <body>
    <main class="main">
      <div>Rigth Indentation</div>
        <div>Wrong Indentation</div>
    </main>
  </body>
</html>
```
``ìndex.js
const Linter = require('lib/Linter)

module.exports = function (options) {
    options = options || {}

    let lint = new Linter(options).lint

    return function PostHTMLLint (tree) {
          tree.walk(node => {
              return lint(node) // no errror => return node / on error => return node, err
          }

          return tree
    }
}
```
***lib/rules/title-no-dup.js***
```js 
let titles = []

exports.title = function (node) {
 if (node.tag === 'title') {
   titles.push(node)
 })

 if (titles.length > 1) {
   let err =  console.log( `${[x:y]: Multiple Titles found (title-no-dup)}`)
   return err
 }

 return node
}
```
```bash
[x:y]: Multiple Titles found (title-no-dup)
```

**lib/rules/indent.js***
```js 
exports.indent = function (node) {
  node.content = node.content.filter((ctx) => typeof ctx === 'string' ? ctx : '')

  node.content.forEach(space => {
     if (space.length !== node.content[i + 1].length {
          let err = console.log(`${[x:y]: Unexpected indentation found (indent)}`)
          return err
     }
  })

 return node
}
```
```bash
[x:y]: Unexpected indentation found (indent)
```

console.log()'s will be replaced with a real reporter (styled output, different error-levels, e.g as warnings, as errors)

htmllint uses htmlparser2 underneath, maybe there are some candies left for us :)

**Comment by michael-ciniawsky** [comment]
@GitScrum welcome :) 👍

**Comment by awinogradov** [comment]
@michael-ciniawsky linter is the good idea!;) You can write about it on medium and others)
