### ISSUE TITLE
parser: option

### ISSUE THREAD

**Issue by danielbayley** [posthtml/posthtml#137]
[PostCSS] has a `parser:` option to choose a different parser to generate the AST ([LESS], [Sass], or _[SugarSS]_ for example) for the rest of the plugins to work on.

Shouldn't PostHTML have the equivalent option to generate it's _PostHTMLTree_?

Then you could use _any_ tempting engine as input.

[Pug][pug] ([formerly Jade][jade]) for example would be something like…
```js
pug = require('pug')
plugins = [
  require('posthtml-plugin')
  require('posthtml-plugin')
]
options =
  //sync: true
  parser: pug

posthtml(plugins)
  .process(html, options)
  .then(function(result) {
    console.log(result.html);
  });
```

I know there is currently [posthtml-jade], but it doesn't work quite as smoothly as it might if there was a _proper_ way of doing this… plus this would add support for other template engines, present and future.

[postcss]: https://github.com/postcss/postcss/blob/master/docs/api.md#processor-class
[pug]: https://github.com/pugjs/pug
[jade]: http://jade-lang.com
[posthtml-jade]: https://github.com/michael-ciniawsky/posthtml-jade
[sass]: https://github.com/postcss/postcss-scss
[less]: https://github.com/gilt/postcss-less
[sugarss]: https://github.com/postcss/sugarss

**Comment by voischev** [comment]
@danielbayley duplicate #101?

**Comment by awinogradov** [comment]
@voischev no. But I think the idea isn't necessary. @danielbayley you can render HTML from any template engine and parse result with posthtml.

``` js
const pug = require('pug');

posthtml([
  require('posthtml-plugin')
])
.process(pug.compile('string of pug', options))
.then(function(result) {
  console.log(result.html);
});
```
