### ISSUE TITLE
Syntax option?

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml#143]
Postcss somewhat recently introduced the ability to pass your own `syntax`, which allowed for [sugarss](https://github.com/postcss/sugarss) to remove brackets and semicolons from css, which is huge. Html seems to me to be a language begging for whitespace significance (a la jade), and I would love to be able to use posthtml with a parser that would allow for this.

Any thoughts/plans on this front? I'd be willing to help out if there's any way that I can!

**Comment by voischev** [comment]
reading this #137 issue.
to budge, first need to support any parser https://github.com/posthtml/posthtml-parser/issues/2.

**Comment by jescalan** [comment]
Ah sorry, I should have found that issue before opening this one. Thanks for the additional details!

**Comment by GitScrum** [comment]
@jescalan maybe you cant help plugins [posthtml-sml](https://github.com/posthtml/posthtml-sml) or [posthtml-jade](https://github.com/posthtml/posthtml-jade) ?

**Comment by voischev** [comment]
release in v0.9.0
