### ISSUE TITLE
Pass file names to posthmtml-postcss for style tags

### ISSUE THREAD

**Issue by web-padawan** [posthtml/posthtml#144]
I try to run `posthtml-postcss` with `stylelint` plugin, to lint inline styles in HTML.
Although `posthtml-postcss` now works [as desired](https://github.com/posthtml/posthtml-postcss/issues/5), it cannot resolve file name. The output looks like this:

```
<input css 1>
3:4     ‼  Expected indentation of 2 spaces (indentation)
```

There should be a file name instead of `<input css 1>`.

**Comment by michael-ciniawsky** [comment]
```js
posthtml( [ postcss() ]).process(file, { from: './src/file.html' })
```

Add `tree.options.from` [here](https://github.com/posthtml/posthtml-postcss/blob/master/index.js#L39). => `options = Object.assign(options, { from: tree.options.from })`

**Comment by Scrum** [comment]
@web-padawan Hi, do you still need help on this?

**Comment by web-padawan** [comment]
Hi, sorry for not being active. IIRC, the reason to request this feature was missing support in Stylelint until 7.3.0 and the root problem is therefore fixed long ago. Feel free to close this issue.
