### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml#147]
If a plugin is processing a node in the tree and runs into a situation where it needs to throw an error, it's generally useful for the user to know where in the source file the error was triggered. Typically this includes at least the filename and line and column number. However, at the moment, plugins don't have access to any of this information.

The line and column number would be a little more difficult (although I still do think important to include). While it wouldn't be too difficult to add these as extra properties on the tag objects in the AST, adding them to strings is more challenging, and would likely mean a massively breaking API change.

The filename on the other hand might be a quicker fix to get developers at least a little bit more context to narrow down where the error is coming from. In theory, we could pass some information about the file currently being processed as a second argument to plugin functions, [here](https://github.com/posthtml/posthtml/blob/master/lib/posthtml.js#L53) perhaps.

**Comment by awinogradov** [comment]
I'll write some ideas about this issue tomorrow. It should be like in postcss

**Comment by awinogradov** [comment]
Will be in plugins: `posthtml-reporter` and `posthtml-browser-reporter`. They will add methods to PostHTML Tree API.

**Comment by markfinger** [comment]
Postcss's error API for plugins is succinct, but works well: http://api.postcss.org/Declaration.html#error

If you've got access to the text, line number and column, babel-code-frame provides some neat reporting: https://github.com/babel/babel/tree/master/packages/babel-code-frame

**Comment by jescalan** [comment]
@markfinger this is exactly [the approach I took](https://github.com/reshape/reshape/blob/master/lib/error.js) - welcome to use this code for posthtml, but it would require a different parser in order to get the line numbers.
