### ISSUE TITLE
Plugin for image replacing

### ISSUE THREAD

**Issue by seokirill** [posthtml/posthtml#148]
Добра!
Есть ли в планах написать плагин, который заменял бы обычные картинки 
```html
<img src="img.jpg" />
```
на что-то вроде
```html
<picture>
    <source srcset="img.webp" type="image/webp">
    <img src="img.jpg" />
</picture
```

**Comment by michael-ciniawsky** [comment]
:+1: for the code, can someone please translate it :) 

[posthtml-inject](https://github.com/posthtml/posthtml-inject) ! WIP

_Current Idea_

```html
<inject img="img.jpg lazy"></inject>
```
```html
<!-- Lazy Load Images with JS -->
<img data-src="img.jpg">
<!-- If JS disabled fallback, needs no extra http request -->
<noscript>
  <img src="img.jpg">
<noscript>
....
....
<script>LazyJS..</script>
```
But nesting multiple images in ```<picture></picture>``` && ```<figure></figure>``` will/should also be supported. 
help out, i 'm currently on it  :)

**Comment by seokirill** [comment]
Heh. I'll try to translate(:

This idea about some legacy code.
With PostCSS we can transpile some legacy or not good css to make it better.
I mean Autoprefixer for example.

Ofc I dont mean some NOT css constructions (which use preprocessors).
And if we talk about html, I mean only html valid constructions, which we can make better.

I think we can compare it with "base64-css", which includes images in css.

Sorry for my Eng(:

**Comment by michael-ciniawsky** [comment]
ahh ok i understand, a prgressive enhancement plugin update older code bases is a nice idea, maybe join some efforts  between posthtml-inject and your plugin :) if you eager to make one, i looking up all kinds of stuff at the moment like meta tags, different images injection, meta facebook/twitter tags, link, the favicon hell, inject lib from npm bower.....If we are aware about older vs. todays 'best practices'  we could easily enable legacy or malformed markup sanitisation

**Comment by awinogradov** [comment]
@michael-ciniawsky do you have plan to support this?

**Comment by michael-ciniawsky** [comment]
not well worked out yet and i dont wanted to 'steal' his idea i was waiting for reply from him

**Comment by awinogradov** [comment]
@seokirill can you explain your idea for @michael-ciniawsky ?

**Comment by michael-ciniawsky** [comment]
i understand the idea it would be something like posthmtml-legacy to upgrade html syntax and semantic but i wanted to wait if he starts a project and answers implementation questions if any if not then a will try to implement it
