### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml#152]
``` js
import { posthtml, plugin, series, parallel } from 'posthtml'

plugin('import', require('posthtml-import')())
plugin('exp', require('posthtml-exp')())
plugin('content', require('posthtml-content')())
plugin('htmlnano' , require('htmlnano')())

posthtml(series('import', parallel('exp', 'content'), 'htmlnano'))
   .process(stream(html), {stream: true})....
```

``` js
import { join } from'path'
import { creatWriteStream } from 'fs'

import express from 'express'
import posthtml from 'posthtml'

const app = express()

const stream = (path, file) => creatWriteStream(join(__dirname, path, file), 'utf8')

app.get('/', (req,res) => {
   res.write(posthtml().process(stream('index.html'), {stream: true})) 
   // write directly to http.response for perf gains (client/server) and memory savings (server)
   res.end()
})
```

**Comment by awinogradov** [comment]
You can convert streams to array for ex. Why not?

**Comment by michael-ciniawsky** [comment]
> You can convert streams to array for ex. Why not?

Is it about the example or you want to notify me of a problem with streams in general? the series and parallel are just prototyping inspiration , maybe unnessecary i basically wanted to mention if this serial and parallel stream processing needs to be considered

**Comment by awinogradov** [comment]
You need the instance of posthtml for every stream in general. Every stream can be converted to the array. To array of files in this case. posthtml can work with them.

**Comment by awinogradov** [comment]
We need big work for this support and I want to understand why we need do this?

**Comment by michael-ciniawsky** [comment]
it's more a benefit for posthtml middlewares when is used to serve html in production you save memory (server), latency and performance gains on the client (browser render process can start earlier, all browsers down to ie6 support streaming). But yes it depends on how big the changes to the code base would be in comparison

**Comment by awinogradov** [comment]
Can you make some analytics about this work?

**Comment by michael-ciniawsky** [comment]
i will start to test and try streams locally with posthtml and mom i have a link and can search for the older ones i read on this matter

**Comment by awinogradov** [comment]
It'll be awesome to see results here ;)

**Comment by jescalan** [comment]
TBH this doesn't seem worth it to me. In production you want to have your templates pre-compiled, and in development the speed increase will be negligible if existent at all. But as long as it's not a breaking API change if someone wants to implement it, it's not an issue.

**Comment by awinogradov** [comment]
It sounds good, but I can speed only from numbers compare. Before 100ms, after 50ms. And you need a plan how to do this. The idea is very good, but we need info about how difficult is to do.
