### ISSUE TITLE
PostHTML in browser

### ISSUE THREAD

**Issue by awinogradov** [posthtml/posthtml#165]

**Comment by awinogradov** [comment]
+1 to webpack ;)

**Comment by michael-ciniawsky** [comment]
👍

**Comment by corysimmons** [comment]
Rollup pls!

**Comment by corysimmons** [comment]
^ party pooper

**Comment by tunnckoCore** [comment]
@jescalan :+1:.

totally not needed. your part of the job is to make as small as possible things, nothing more. :)

**Comment by michael-ciniawsky** [comment]
@awinogradov @voischev Should a browser build been added  with webpack/rollup or can this be closed. Personally I'm in favor to other folks make their own build if the need it. posthtml-render is already browser friendly and rendering the tree only is the better solution for browser usage in my opinion. Then close please :)
