### ISSUE TITLE
How should posthtml plugins push warnings?

### ISSUE THREAD

**Issue by jonathantneal** [posthtml/posthtml#185]
When something does not go as expected in a posthtml plugin, is there an appropriate place to put our errors, [like there is in postcss](http://api.postcss.org/Node.html#warn), or should we pushing our own errors to the console?

**Comment by jescalan** [comment]
PR #159 included a pretty robust error handling feature for plugins, but it wasn't accepted. If the maintainers wanted, that feature might be able to be extracted, but it would probably need to come with some breaking changes in order to lay the groundwork for proper error reporting.

**Comment by awinogradov** [comment]
@jonathantneal we have #147 and plans to support PostCSS way ;)
