### ISSUE TITLE
PostHTML Mixins

### ISSUE THREAD

**Issue by mrmlnc** [posthtml/posthtml#190]
Hello,

/cc @michael-ciniawsky @voischev 

I wrote a very dirty prototype of the plugin for support Mixins. I'd like to get feedback on Mixin syntax and look at your ideas. How do you see the syntax of Mixins in your project?

Very dirty demo: https://github.com/mrmlnc/posthtml-mixins-demo

**Comment by mrmlnc** [comment]
Some questions:

  * `<mixin name="one">` or `<mixin id="one">`
  * `<mixin name="one">` or `<m-one>`
  * Support Mixin reloading? For example,

    ```
    <mixin name="one">...</mixin>
    <mixin name="one" paramName>...</mixin>
    ```

**Comment by michael-ciniawsky** [comment]
👍  I will take a look at it soon 😛

**Comment by michael-ciniawsky** [comment]
>  `<mixin name="one">` or `<mixin id="one">`

If one needs to be chosen, then personally I'm in favour of `<mixin name="">, but both at best interchangeable :).

Additionally, maybe something like 

```
<mixin name="button" id="[hash 1]"></mixin>  // mixins/button_[1].html
<mixin name="button" id="[hash 2]"></mixin> // mixins/button_[2].html
```

in the direction like CSS Modules do it. but it's just a rough idea/prototype atm :)

> Support Mixin reloading? For example

? :) 😛 

Looks very nice so far 👍

**Comment by mrmlnc** [comment]
> personally I'm in favour of `, but both

Yes! I think so too.

> Support Mixin reloading? For example
> ? :) 😛

If the Mixins have the same name, but a different number of parameters is a various Mixins (as in Less).

**Comment by michael-ciniawsky** [comment]
> If the Mixins have the same name, but a different number of parameters is a various Mixins (as in Less).

I'm not too familar with LESS, but I think I got it :). My idea is really rough and unmature, can even be possible, that this feature is not needed at all 😛

**Comment by mrmlnc** [comment]
Closed by https://github.com/mrmlnc/posthtml-mixins.
