### ISSUE TITLE
[docs]: from/to options documentation

### ISSUE THREAD

**Issue by stevenvachon** [posthtml/posthtml#197]
Like postcss [has](https://github.com/postcss/postcss#options).

**Comment by michael-ciniawsky** [comment]
@stevenvachon `posthtml-include [v2.0.0](https://github.com/posthtml/posthtml-include/pull/16) && posthtml-content [v1.0.0](https://github.com/posthtml/posthtml-content/pull/4) will support `tree.option.from` && `tree.options.to`, you can use them today in your plugins, but none of the existing plugins support them atm, but its avialable in posthtml just lacking [docs](https://github.com/posthtml/posthtml/issues/188)

```js
posthtml([ plugin () ]).process(html, { from; './src/file.html', to: 'dest/file.html' })
```

```js
module.exports = (options) => {
   return posthtmlPlugin (tree) {
      console.log(tree.options.from) // './src/file.html'
      console.log(tree.options.to) // './dest/file.html'
   }
}
```

**Comment by stevenvachon** [comment]
Thanks! Renaming this issue.
