### ISSUE TITLE
challenge setting the posthtml.process() options

### ISSUE THREAD

**Issue by revelt** [posthtml/posthtml#208]
I'm using PostHTML on HTML for email templates, which is XHTML, which means I need closing slashes on singleton tags. 

`postHTML.process(html, options)` does let us override the renderer. My thinking is, if we could pass the same `posthtml.render` but with settings `{ closingSingleTag: 'slash' }`, I'd get the closing slashes. However, it seems not possible.

**Check this out:**

In Gulp, I call `gulp-posthtml` (bear with me, it's a `posthtml` API issue):

```js
var options = { closingSingleTag: 'slash' }
...
.pipe(posthtml(plugins, options))
```

Then, it calls `posthtml.process()` passing `options` as second argument:

```js
posthtml(plugins)
        .process(file.contents.toString(enc), options)
        .then((result) => {
```

However, according to the [API documentation](https://github.com/posthtml/posthtml/blob/master/docs/core.md#posthtml-options), `.process` accepts only `options.render`, the render _function_ override.

But we can't set options to it:

```js
posthtml(plugins)
        .process(file.contents.toString(enc), { render: posthtml.render(WHAT_GOES_HERE_?, { closingSingleTag: 'slash' }) })
        .then((result) => {
```

I might be missing something elementary, but currently it seems there's no easy way to customise the PostHTML rendering. I just want slashes/no slashes option, `closingSingleTag ` (while we're at it, we could add `posthtml-render`'s `singleTags` too). The `posthtml-render` has only two options arguments anyway, so it would be relatively easy to tap them straight in `posthtml.process()`, wouldn't it?

I know I mentioned `gulp-posthtml` and it might seem like this issue belongs to a different repo, but it does not, currently I believe `postHTML.process` needs additional options to mimic those of `posthtml-render`.

If you know any solution how to get my closing slashes back, I'd be grateful for any suggestions.

**Comment by voischev** [comment]
hi! 👋
whi not 
```
.pipe(posthtml(plugins, options))
.pipe(posthtml(plugins2, options2))
```
?

**Comment by revelt** [comment]
hi Ivan

The problem is, I don't know how to plug the `{ closingSingleTag: 'slash' }`

We can't put it like:
```js
.pipe(posthtml(plugins, { closingSingleTag: 'slash' }))
```
can we?

**Comment by voischev** [comment]
In this case, did not pass this test https://github.com/posthtml/posthtml/blob/master/test/options.js 
maybe problem in `gulp-posthtml`

**Comment by revelt** [comment]
hi again,

I'm having closing slash troubles on one of my PostHTML plugins, [posthtml-color-shorthand-hex-to-six-digit](https://www.npmjs.com/package/posthtml-color-shorthand-hex-to-six-digit) and there is no Gulp involved. Have a look:

### `index.html`:
```
'use strict'
var colorHexConvert = require('color-shorthand-hex-to-six-digit')

module.exports = function () {
  return function removeUnusedCss (tree) {
    tree = colorHexConvert(tree)
    return tree
  }
}
```

### `test.js`:
```js
'use strict'

const test = require('ava')
const plugin = require('..')
const {readFileSync} = require('fs')
const path = require('path')
const posthtml = require('posthtml')
const fixtures = path.join(__dirname, 'fixtures')

function compare (t, name, opts) {
  const html = readFileSync(path.join(fixtures, `${name}.html`), 'utf8')
  const expected = readFileSync(path.join(fixtures, `${name}.expected.html`), 'utf8')
  return posthtml([plugin()])
    .process(html, opts)
    .then((res) => t.deepEqual(res.html, expected))
}
test('respects XHTML files and doesn\'t remove closing slashes', (t) => {
  return compare(t, 'xhtml', { closingSingleTag: 'slash' })
})
```

API library, [color-shorthand-hex-to-six-digit](https://github.com/codsen/color-shorthand-hex-to-six-digit) does not mangle the closing slashes, proven by its unit test number 07.02 I just committed this morning.

There's something wrong with PostHTML settings, or I'm setting the plugin wrongly.

Can somebody advise please?

Thank you.

**Comment by GitScrum** [comment]
@revelt close this issue ?

**Comment by revelt** [comment]
definitely, forgot about this-one

**Comment by revelt** [comment]
thanks for all support!
