### ISSUE TITLE
the problem of config of webpack

### ISSUE THREAD

**Issue by nicholaslee119** [posthtml/posthtml#209]
I just copy the example of readme to my vue-cli-based project.

```js
new LoaderOptionsPlugin({
       options: {
         posthtml (ctx) {
          parser: require('posthtml-pug')
          plugins: [
            require('posthtml-include')({ root: ctx.resourcePath })
          ]
        }
      }
    })
```

```bash
$npm run dev
```

and here is the error

```js
Module build failed: Error: Configuration must return an array or object!
    at Object.parseOptions (/node_modules/posthtml-loader/lib/index.js:35:11)
    at Object.module.exports (/node_modules/posthtml-loader/lib/index.js:12:27)
```

maybe there are some typo with that?

thanks for your reading

**Comment by michael-ciniawsky** [comment]
Yep please wait a few moments I have a fully webpack 2 compatible version locally :) Just finish release

**Comment by nicholaslee119** [comment]
Thanks for your reply,
anyway, I fix it by myself. :-)

**Comment by michael-ciniawsky** [comment]
@nicholaslee119 Sry for the delay I'm workin on  posthtml-loader `v1.0.0` it's nearly finished (docs, cleanup a few nits) you can try it by pulling from master directly. Sure I will take a look in a sec :)

### Setup

**package.json**
```json
{
   "devDependencies": {
      "posthtml-loader": "posthtml/posthtml-loader"
    }
}
```


**webpack.config.js**
```js
// Parser
{
   loader: 'posthtml-loader', options: { parser: 'posthtml-sugarml/posthtml-pug' }
}

// Plugins
{
   loader: 'posthtml-loader', options: { plugins: () => [...plugins] }
}

// Config
// Looks up the config automatcially
{
   loader: 'posthtml-loader', options: {} } 
}
// Set path to config explicitly e.g when in ./config folder
{
   loader: 'posthtml-loader', options: { 
       config: { path: 'path/to/posthtml.config.js', ctx: { expressions: false } } 
   }
}
```

[**posthtml.config.js**](https:// github.com/posthtml/posthtml-load-config)  (recommended)
```js
module.exports = ({ file, options, env }) => { // webpack.options.ctx === options
    parser: 'posthtml-sugarml'
    plugins: {
      'posthtml-include': { root: file.dirname },
      'posthtml-expressions': options.expressions,
      'htmlnano': env === 'production' ? {} : false
    }
}
```

#### Templates

**webpack.config.js**
```
// Exports a function => (_) => `${html}`
{
   loader: 'posthtml-loader', options: { template: true } }
}
```

**component.html**
```html
<h1 class="hello">${ _.hello }</h1>
```

**component.js**
```js
import template form './component.html'

document.body.innerHTML = template({ hello: 'Hello World' })
```

⚠️  `posthtml-loader` is webpack v2 only and doesn't require `html-loader` anymore, it exports a module directly

**Comment by nicholaslee119** [comment]
great job!
Thanks for that!!

**Comment by michael-ciniawsky** [comment]
@nicholaslee119 😛 Thx, please use ` { loader: '...', options: { plugins: [...plugins] } }`  `{Array}` for now, bc I haven't updated the Loader Options Validation Schema yet :D. Will be fixed in the release 1-2 days 🙏

**Comment by Shyam-Chen** [comment]
I use `posthtml-bem` plugin, but can not work.

My boilerplate is [here](https://github.com/Vanilla-IceCream/Webpack-GO).

**Comment by michael-ciniawsky** [comment]
@Shyam-Chen You use `posthtml-loader` v0.11.0 which doesn't support webpack 2 syntax, I'm working on `v1.0.0` like mentioned above, but being busy with daily work and @webpack-contrib atm 🙃 . I need to fix an outstanding bug in `posthhtml-load-config`  before I can finish the v1.0.0 release of the loader, I  will do it as soon as possible, but please be patient 😛 .Also in the optimal case I need to finish #195 aswell, to get partial/includes  **auto** watching to work properly. Meanwhile you can try `v1.0.0` by installing directly from the master branch. should work but not 💯  bug free on the edges

**package.json**
```diff
{
   "devDependencies": {
-       "posthtml-loader": "^0.11.0"
+      "posthtml-loader": "posthtml/posthtml-loader"
    }
}
```

**webpack.config.js**
```js
{
   loader: 'posthtml-loader',
   options: {
     plugins: [
       bem({ elemPrefix: '__', modDlmtr: '--', modPrefix: '-' }),
       // inlineAssets(),
       minifier()
     ],
     template: true
  }
}
```

⚠️  You can use `html-loader`, but it's not mandatory anymore `posthtml-loader` >= `v1.0.0` will export a module directly, so if you don't use any functionality from it, like it seems to be the case in your example (you minify already via posthtml plugin) drop it :) for faster builds

**Comment by GitScrum** [comment]
@nicholaslee119 @Shyam-Chen Hi, i fixed readme but `posthtml-loader` v0.11.0 is still available bug. 
If you're still experiencing problems let me know and I'll try to create a new `boot loader` efficiently. @michael-ciniawsky  does not get in touch.

**Comment by GitScrum** [comment]
@nicholaslee119 @Shyam-Chen i create  [example](https://github.com/inside-demo/posthtml-loader-demo) using posthtml-loader

**Comment by GitScrum** [comment]
@Shyam-Chen @nicholaslee119 close this issue ?

**Comment by nicholaslee119** [comment]
OK, Thank you!
