### ISSUE TITLE
php code is getting removed

### ISSUE THREAD

**Issue by stevecfischer** [posthtml/posthtml#212]
Is there any way to exclude or whitelist the ```<?php ?>``` tags? 

here is my input:
```
<div class="header">
	<?php header(); ?>
</div>
<h2 id="title" class="h2">Hello World</h2>
<div class="footer">
	<?php footer(); ?>
</div>
```

and here is the output:
```
<div class="header">
	
</div><!-- /.header -->
<h2 id="title" class="h2">Hello World</h2><!-- /#title.h2 -->
<div class="footer">
	
</div><!-- /.footer -->
```
## Look at those glorious auto generated comments!!! ##

I want to use many of the posthtml tools. Most importantly I REALLY want to use the posthtml-comment-after and the posthtml-bem plugins. But my PHP code is here to stay there is no going around that. So if there is anything that can be done to skip over php code it would be awesome.

**Comment by michael-ciniawsky** [comment]
Yeah seems to be a bug, but I haven't had time yet to investigate futher

**Comment by stevecfischer** [comment]
I'm going to take that as good news. And hopefully its a simple bug to resolve. I tried looking in the code to figure out where the php code is getting dropped but couldn't figure it out. If you point me in a certain direction that could help too.

**Comment by stevecfischer** [comment]
^bump

**Comment by GitScrum** [comment]
@stevecfischer Hi, see https://github.com/posthtml/posthtml-parser/pull/16 - this must help you

**Comment by yustnip** [comment]
@GitScrum Is it enough to add this now (directives)?
```
gulp.task('templates', function() {
  var bemConfig = {
    elemPrefix: '__',
    modPrefix: '_',
    modDlmtr: '--'
  }
  var plugins = [posthtmlBem(bemConfig)]
  var options = {
    directives: [
      { name: '?php', start: '<', end: '>' }
    ]
  }

  return gulp.src('./templates/*.php')
    .pipe(posthtml(plugins, options))
    .pipe(gulp.dest('./'))
})
```

**Comment by GitScrum** [comment]
@yustnip No, [i work on this](https://github.com/posthtml/posthtml/issues/230).

**Comment by GitScrum** [comment]
@yustnip @stevecfischer https://github.com/posthtml/posthtml/pull/231.
close this issue after merge PR ?

**Comment by yustnip** [comment]
@GitScrum I think it can be closed after the merge.

**Comment by GitScrum** [comment]
@yustnip @stevecfischer try

**Comment by yustnip** [comment]
@GitScrum Unfortunately can't check it now because I use gulp-posthtml and it is outdated now. I've made the PR for it - https://github.com/posthtml/gulp-posthtml/pull/10

**Comment by yustnip** [comment]
@GitScrum 
I have some trouble if use it with gulp-posthtml. My config - https://github.com/yustnip/inception-base/blob/master/gulpfile.js

It works only if I add the second arg to the parser function inside posthtml - https://github.com/yustnip/posthtml/blob/feature/options-to-parser/lib/index.js#L97

Is it required to update the posthtml module? Or my gulp config is wrong?

**Comment by GitScrum** [comment]
@yustnip i see tomorrow )

**Comment by GitScrum** [comment]
@yustnip Hi,
1. https://github.com/yustnip/inception-base/blob/cba85804c030368b24cd1ea1d347e49218a17a93/gulpfile.js#L26 - this folder is empty (
2. https://github.com/yustnip/inception-base/blob/cba85804c030368b24cd1ea1d347e49218a17a93/package.json#L21 - not need. `posthtml` goes with `gulp-posthtml`.
3. https://github.com/yustnip/inception-base/blob/cba85804c030368b24cd1ea1d347e49218a17a93/package.json#L16 - you not update `gulp-posthtml` to version v3.0.1
4. > It works only if I add the second arg to the parser function inside posthtml
You right )

**Comment by yustnip** [comment]
@GitScrum Hi,

1-3. Thanks for your notices. :) Now this changes is pushed to the repo. But however it doesn't work without changing the posthtml module inside node_modules directory.

4. Are you going to make changes?

**Comment by GitScrum** [comment]
@yustnip https://github.com/posthtml/posthtml/pull/234 - this fix four point and need prepare https://github.com/posthtml/posthtml/issues/233

**Comment by yustnip** [comment]
@GitScrum Cool!

**Comment by yustnip** [comment]
@GitScrum Seems it works now. Thanks a lot!
