### ISSUE TITLE
Escape character (Lodash template `<% %>`)

### ISSUE THREAD

**Issue by Shyam-Chen** [posthtml/posthtml#216]
Need to escape Lodash template syntax (`<% %>`).

```html
<p>
  <%= foo %>
<p>
```

```js
import { template as _ } from 'lodash';

import template from './foo.html';

console.log(_(template)({ foo: 'Foo' }));
```

**Comment by GitScrum** [comment]
@Shyam-Chen Hi, see https://github.com/posthtml/posthtml-parser/pull/16 - this must help you.

**Comment by GitScrum** [comment]
@Shyam-Chen https://github.com/posthtml/posthtml/pull/231.
close this issue ?

**Comment by Shyam-Chen** [comment]
Awesome!

**Comment by Shyam-Chen** [comment]
After the release, I will do the test.

**Comment by GitScrum** [comment]
@Shyam-Chen try

**Comment by GitScrum** [comment]
@Shyam-Chen close ?
