### ISSUE TITLE
A few parsing issues

### ISSUE THREAD

**Issue by 7immy** [posthtml/posthtml#22]
I've notice a few errors with the below code while parsing through postHTML..

In this example only one of the div's get output into the tree:
```
<div class="wow">
    one
</div>
<div class="wow">
    two
</div>
```

In this example only the class attribute is being recognised
```
<div class="wow" id="IDs-dont-get-recognised" role="test" data-test="hello" doiexist="umm">
    two
</div>
```

Is this a bug, features yet to be implemented or by design?

Cheers :)

**Comment by voischev** [comment]
This a bug. Issue duplicate #19 
Thanks for report!
