### ISSUE TITLE
rollup example

### ISSUE THREAD

**Issue by petulla** [posthtml/posthtml#223]
can you provide an example of how to do this with rollup please?

**Comment by Shyam-Chen** [comment]
https://github.com/Vanilla-IceCream/rollup-plugin-posthtml-template

**Comment by tunnckoCore** [comment]
There is [tunnckoCore/rollup-plugin-posthtml](https://github.com/tunnckoCore/rollup-plugin-posthtml). I don't know why is this duplication. This "template" thing don't make any sense, and it uses `lodash`.

**Comment by Shyam-Chen** [comment]
https://github.com/Vanilla-IceCream/rollup-plugin-reshape
