### ISSUE TITLE
Hot to get parent of current node in walk()

### ISSUE THREAD

**Issue by cronfy** [posthtml/posthtml#226]
I can't realize how to get parent of current node in `walk()/match()`.

My use case is following:

 1. Find all `input`s.
 2. Check it against simple contraints: it must have `form` in one of it's parents and it must have `label` among it's siblings.
 3. If constraints are not met, throw an error.

Currently I can find `input`s with `match()`, but how do I check it has `form` parent?

**Comment by voischev** [comment]
You should find parent first, and find inputs in parent tree.

Example
```js
var match = tree.match;
tree.match({ tag: 'form' }, node => {
    match.call(node, cb);
});
```

**Comment by cronfy** [comment]
The problem is that input can be not in form. I want to check exactly this: that all inputs are in forms, and throw an error if it is not like that.

Currently I wrote simple plugin that creates links to parent. What do you think - should this be a plugin or a core functionality?

E. g. in PostCSS every node has a parent: http://api.postcss.org/Node.html#parent

Plugin:

```
'use strict';

module.exports = function () {
    return function MarkParent (tree) {
        tree.walk(function (node) {
            for (var i in node.content) {
                var current = node.content[i]

                if (!current.tag) {
                    continue
                }

                current.parent = node;
            }

            return node;
        })

        return tree
    }
}

```

**Comment by voischev** [comment]
this complication and allows not to solve the problem optimally. 
```<form><div><input>``` = parent.parent :( 

```js
var match = tree.match,
    count = 0;

tree
    .match({ tag: 'form' }, node => {
        match.call(node, { tag: 'input' }, input => {
            input._inForm = true;
            return input;
        });
    })
    .match({ tag: 'input', _inForm: false }, node => { 
        count++;
        return node;
    });
```

**Comment by cronfy** [comment]
Ok, it works.

But why `_inForm: true` does not work?

```
            .match({ tag: 'input', _inForm: true }, node => {
                count++;
                return node;
            });
```

`count` is always 0.

**Comment by voischev** [comment]
🤔 Should be works
https://github.com/posthtml/posthtml/blob/master/test/api.js#L239-L248

mb?
```js
.match({ tag: 'form' }, node => {
        match.call(node, { tag: 'input' }, input => {
            input._inForm = true;
            return input;
        });
        return node; // <-----------------
    })
```

**Comment by cronfy** [comment]
Yes, `return node;` solved it.

Thank you!

**Comment by GitScrum** [comment]
@cronfy close this issue ?

**Comment by cronfy** [comment]
You decide :) I am satisfied with your solution and my plugin.
