### ISSUE TITLE
API

### ISSUE THREAD

**Issue by TrySound** [posthtml/posthtml#23]
Suggest to add `.each(selector, callback)` method. It's the most usable thing to transform html.

**Comment by verybigman** [comment]
:+1:

**Comment by TrySound** [comment]
We can go by cheerio way and use htmlparser2 directly

**Comment by voischev** [comment]
and be ;)

**Comment by voischev** [comment]
TODO: `.parent()` method

**Comment by voischev** [comment]
Look at base API PR https://github.com/posthtml/posthtml/pull/31/files

**Comment by voischev** [comment]
Close in https://github.com/posthtml/posthtml/commit/096654a61f6b3fb082da67dca52a07fd496ba30a
