### ISSUE TITLE
webpack live reload when include changes

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml#254]
I am not sure where to go with this issue. When I change contents of included file (using ```posthtml-include```) I get no recompiling and no live page reload. I suspect it may be "normal" for such use cases, i.e. with usage of includes/extends in template engines within webpack ecosystem (for example https://github.com/pugjs/pug-loader/issues/75). Can you give any hints where to start?

**Comment by michael-ciniawsky** [comment]
See https://github.com/posthtml/posthtml-include/pull/16 which adds this functionality to the plugin :) the loader already supports it since `>= v1.0.0`. If you like try it out `npm/yarn install michael-ciniawsky/posthtml-include` any feedback appreciated.

**Comment by andreyvolokitin** [comment]
Works, but if used in conjunction with ```posthtml-beautify``` there is no recompiling (and no visible errors) after changes in included file

**Comment by GitScrum** [comment]
@andreyvolokitin Hi, show me your example where tou use `posthtml-beautify`

**Comment by andreyvolokitin** [comment]
Will do later, but it is pretty much any use case of ```posthtml-beautify``` in conjunction with some other plugin which uses ```tree.messages``` posthtml API (i.e. ```michael-ciniawsky/posthtml-include```), see: https://github.com/GitScrum/posthtml-beautify/issues/211

**Comment by GitScrum** [comment]
@andreyvolokitin close this issue ?

**Comment by andreyvolokitin** [comment]
Probably yes, hope this gets merged soon https://github.com/posthtml/posthtml-include/pull/16
