### ISSUE TITLE
posthtml-include vs posthtml-modules

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml#255]
It seems like ```posthtml-include``` is more mature than  ```posthtml-modules```, but ```posthtml-modules``` has all functionality of ```posthtml-include``` and more. Would it make sense to merge them into one?

**Comment by michael-ciniawsky** [comment]
Yes, both are quite similar indeed. The only difference is that `posthtml-modules` works recursively and it's possible to transform the includes/modules **while** importing them (e.g CSS Modules). `posthtml-include` only parses the includes and the transforms happen in the 'main chain' **after** importing. `posthtml-modules` also doesn't support dependency tracking at all atm
