### ISSUE TITLE
[bug] no-value-attrs has been parsed to Empty String

### ISSUE THREAD

**Issue by jiangjiu** [posthtml/posthtml#263]
> 

 no-value-attrs has been parsed to Empty String, but i want it back to raw.

### `Details`

>
script:

```js

posthtml().process(input).then(result => console.log(result.html))
```

input :
 
```js
 <p  class="title" aaa bbb ccc>123</p>
```

parsed:

```js
 <p  class="title" aaa='' bbb='' ccc=''>123</p>
```

### `Environment`

> ℹ️ Please provide information about your current environment.

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|mac 10.12|v8.9.3|yarn 1.5.1 |latest|

**Comment by jiangjiu** [comment]
i know browsers will ignore the empty string......but the template that i parsed is just a middle-layer-ast, my framework will process this template into the final html, same as Vue's template && vue-loader

**Comment by michael-ciniawsky** [comment]
https://github.com/posthtml/posthtml-render/blob/master/lib/index.js#L135

```js
if (obj[key] === '') {
  attr += ' ' + key
} else {
  attr += ' ' + key + '="' + obj[key] + '"'
}
```

Untested && maybe a better check then `if (obj[key] === '')` is needed and so on... :) Test it locally by editing `node_modules/posthtml-render/lib/index.js` at best and PR welcome

**Comment by jiangjiu** [comment]
![image](https://user-images.githubusercontent.com/9526388/37448034-96af1bc8-285f-11e8-8a62-55fa2a3a1da4.png)


![image](https://user-images.githubusercontent.com/9526388/37448017-8b2500b0-285f-11e8-8e1c-f45136c744fa.png)

obviously the problem is in parsing process....

how can parser  mark out `attr` and `attr=""`?

**Comment by michael-ciniawsky** [comment]
What's the problem with the `attr: ''` representation for `{Boolean}` attributes in the AST ? The alternative would be `attr: true` which would require changes to the generator (`posthtml-render`) and is potentially a breaking change for minimal benefit. Could you describe your use case a bit further please and can't AST part not be handled by your framework ?

**Comment by michael-ciniawsky** [comment]
The change to the generator should I proposed in my first comment should give you the following result 

**input.html**
```html
<div id="1" class="box" hidden></div>
```

**PostHTML AST**
```js
{
   tag: 'div',
   attrs: { id: '1', class: 'box', hidden: '' }
   content: []
}
```

### with https://github.com/posthtml/posthtml/issues/263#issuecomment-373253092

**output.html**
```html
<div id="1" class="box" hidden></div>
```

### without https://github.com/posthtml/posthtml/issues/263#issuecomment-373253092 (Current)

**output.html**
```html
<div id="1" class="box" hidden=""></div>
```

The generator (`posthtml-render`) outputs `{Boolean}` attributes as `attr=''`, which could be fixed by applying  (in the direction of) my suggested changes

**Comment by jiangjiu** [comment]
thanks for your help~

but i think i didn't point the key problem....

i can render a `attr:true` into a `attr` like this:
ast:

```js
{
   tag: 'div',
   attrs: { id: '1', class: 'box', hidden:true}
   content: []
}
```

output:

```js
<div id="1" class="box" hidden></div>
```

**that's cool, that's exactly what I want。but, that's the render process,.... now let's pay attention to parse process**


from input to ast, parser cannot tell the diffrence from `attr` and `attr=""`

when i give a element like this:

```js
<p emptyattr emptystring="">123</p>
```

parsed ast:

```js
{
   tag: 'p',
   attrs: { emptyattr: '', emptystring: ''}
   content: ['123']
}
```

that means: when posthtml parsed, i lost the diff between `emptyattr` and `emptystring`....

**Comment by Scrum** [comment]
probably this option will suffice [singletags](https://github.com/posthtml/posthtml-render#singletags) ?

**Comment by jiangjiu** [comment]
@Scrum my problem is in parse phase... not render

**Comment by michael-ciniawsky** [comment]
```
<div hidden>
```

```
{ hidden: '' } // PostHTML Parser (HTMLParser 2)
{ name: 'hidden', value: '' } // Parse5
```

So this would need to be handled in `posthtml-parser` around [here](https://github.com/posthtml/posthtml-parser/blob/master/index.js#L90), but there is no way to distinguish between `<div empty='' boolean>` nevertheless due to the underlying parser. I personally don't think this is a valuable change and you should reconsider relying upon that logic...

**Comment by jiangjiu** [comment]
yeah, i scaned parse5 && htmlparse2 's code,   there is no way to distinguish between `<div empty='' boolean> `...

thanks ~ i'll find how to get it works

**Comment by PaulMaly** [comment]
@jiangjiu Hi! Can you give me advise on how to fix a similar issue?

**Comment by jiangjiu** [comment]
> @jiangjiu Hi! Can you give me advise on how to fix a similar issue?

maybe it's a false demand...
