### ISSUE TITLE
Can I use this to transpile html within ES6 template literals?

### ISSUE THREAD

**Issue by AndyOGo** [posthtml/posthtml#268]
> ✏️ Briefly describe the issue you are experiencing (or the feature you want to see added to the plugin). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/posthtml/posthtml

### `Details`

I have JS code like:

```js
const template = ({ className, title }) => html`
  <div class="${className}">
    <h1>${title}</h1>
  </div>
`;

export default template;
```
And I want to PostHTML just that html portion within the ES6 template lit.

Is this possible?

> ✏️ Describe in more detail the problem you have been experiencing, if necessary.

**Comment by GrosSacASac** [comment]
I don't think it is possible as is, posthtml accepts only html as input. Its responsability is not to detect html strings inside js. Have a look at acorn and babel js parser. These have options to include plugins to transform the code after it is parsed. Inside that plugin, posthtml could be used. Or use a regular expression.

**Comment by AndyOGo** [comment]
@GrosSacASac 
Thank you for your quick answer.
You are right, it would need to be a part of the transpilation process.

**Comment by Scrum** [comment]
@AndyOGo close this issue ?

**Comment by Scrum** [comment]
@AndyOGo ping

**Comment by AndyOGo** [comment]
@Scrum 
Thanks for asking me, well if you not consider within the scope of this project, sure.
Meanwhile I though of a babel plugin, if possible 🤔
