### ISSUE TITLE
[fix]: Inlined SVG - Wrong html output when a <animate> tag is inside a <stop> tag

### ISSUE THREAD

**Issue by MarlBurroW** [posthtml/posthtml#269]
When a SVG is inlined in the HTML and contains a \<animate> tag inside a \<stop> tag, the \<animate> is wrapped out of the \<stop> tag in the output file.

### `Details`

I found this issue using parcel-bundler: https://github.com/parcel-bundler/parcel/issues/1758

### `Reproduction (Code)`

Create a simple `index.js` file with the below code

```javascript
posthtml = require('posthtml')

const html = `
<svg version="1.1"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
      <linearGradient>
          <stop>
              <animate></animate>
          </stop>
      </linearGradient>
  </defs>
</svg>
`

const result = posthtml()
  .process(html, { sync: true })
  .html

console.log(result)
```
And run it:
```bash
$ node index.js
```
Expected output:

```html
<svg version="1.1"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
      <linearGradient>
          <stop>
              <animate></animate>
          </stop>
      </linearGradient>
  </defs>
</svg>
```

Current output:

```html
<svg version="1.1"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
      <linearGradient>
          <stop></stop>
              <animate></animate>
      </linearGradient>
  </defs>
</svg>
```

### `Environment`

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|OSX High Sierra|8.6.0|5.6.0|0.11.3|

**Comment by Scrum** [comment]
@MarlBurroW Hi, thanks for the feedback. I will try to deal with this problem. Sorry for so long.

**Comment by Scrum** [comment]
@MarlBurroW Looks like it was fixed, try updating the post version and try again.

Let me know if something goes wrong.

**Comment by MarlBurroW** [comment]
@Scrum Yes it works fine (tested with v0.11.2).
This issue can be closed now, thank you very much for your work!
