### ISSUE TITLE
[docs]: Broken links in README

### ISSUE THREAD

**Issue by fstanis** [posthtml/posthtml#270]
It seems the following links in the README are broken:

- https://github.com/posthtml/posthtml-collect-styles
- https://github.com/code-and-send/posthtml-color-shorthand-hex-to-six-digit
- https://github.com/seokirill/posthtml-webp
- https://github.com/code-and-send/posthtml-email-remove-unused-css

Should we go ahead and remove them?

**Comment by voischev** [comment]
hi 👋. yes plz!
