### ISSUE TITLE
not rendering html while using plug-ins 

### ISSUE THREAD

**Issue by Mr-Manna** [posthtml/posthtml#272]
> Whenever I am using posthtml with gulp or webpack  none of the plug-ins are rendering html properly but no error there.

 `my gulp task`

```
gulp.task('html', () => {
      gulp.src('./src/*.pug')
        .pipe(pug())
        .pipe(posthtml())
        .pipe(rename( { extname: '.html' }))
        .pipe(gulp.dest('./build'))
});
```

`posthtml.config.js`

```
module.exports =({
  parser: 'posthtml-pug',
    plugins: {
     'posthtml-alt-always' : {},
    'postcss-svgo':{},
     'posthtml-w3c':{},
     'posthtml-schemas': {},
    'posthtml-minifier' : {}
    }
})
```

### `Environment`

|OS|node|npm|gulp|
|:-:|:--:|:-:|:------:|
|[windows]|[8.11.3]|[6.1.0]|[3.9.1]|

**Comment by Scrum** [comment]
@Mr-Manna  Hi, watch carefully how plugins connect https://github.com/posthtml/posthtml#gulp

If you do not succeed, post your example on the githab and I will try to help you

**Comment by Mr-Manna** [comment]
Hi @Scrum ,
Thanks for your kind attention.
This is a minor issue with the posthtml-config file. 
```
module.exports =({
    plugins: {
    'posthtml-minifier' : {}
    }
})
```
the above setting is causing issue while I'm not using any  plugin option . If I add options , there is no issue and it's working fine. The below setting is working fine.
```
module.exports =({
    plugins: {
    'posthtml-minifier' : { removeComments: true }
    }
})
```
