### ISSUE TITLE
[perf]: add TypeScript typings

### ISSUE THREAD

**Issue by metonym** [posthtml/posthtml#288]
Are there any plans to add TypeScript types for `posthtml`?

The main benefit would be to enhance the developer experience for writing `posthtml` plugins.

**Comment by Scrum** [comment]
@metonym Hi, yes - this is a good premise, I plan it in the near future but I hope that maybe you will be faster))

**Comment by metonym** [comment]
Thank you – wanted to confirm that there wasn't already an effort underway.

**Comment by Scrum** [comment]
@metonym Thank you for your good contribution, we appreciate any help
