### ISSUE TITLE
Add possibility to include plugins using ternary operator

### ISSUE THREAD

**Issue by vladshcherbin** [posthtml/posthtml#296]
### Details

It would be nice to be able to include plugins like this:

```js
const production = false

await posthtml([
  insertAt(...),
  production && beautify(...)
])
```

I'm using [rollup](https://rollupjs.org/) and it's possible to define plugins there this way which is very convenient.

Tried same in posthtml but got errors.

**Comment by voischev** [comment]
@vladshcherbin 

```js
const production = false

await posthtml([
  insertAt(...),
  production && beautify(...)
].filter(Boolean))
```

**Comment by vladshcherbin** [comment]
@voischev yeah, I know about workarounds, same here:

```js
const production = false

await posthtml([
  insertAt(...),
  ...(production ? [beautify(...)] : [])
])
```

However, it would be awesome to have this working with nice and simple syntax. I believe it's just a check for a function and if not, skip it.

**Comment by Scrum** [comment]
if you do an iterable check on all plugins, this will only increase the performance time. It seems to me that the correct preparation of the config should not be part of the kernel.

**Comment by vladshcherbin** [comment]
@Scrum I've checked how rollup is doing it and it has a [simple filter call](https://github.com/rollup/rollup/blob/v1.23.1/src/rollup/index.ts#L76), same as proposed above.

I believe same filter can be added [here](https://github.com/posthtml/posthtml/blob/v0.12.0/lib/index.js#L27) and it won't add any performance regressions.

**Comment by Scrum** [comment]
I understand correctly what you want so?
```js
this.plugins = typeof plugins === 'function' ? [plugins] : plugins.filter(Boolean) || []
```

in this case, you have to go around the whole list, which will entail a waste of time

**Comment by vladshcherbin** [comment]
@Scrum yes

I believe you don't use 100 plugins, more like 1-10 and will never see a few added ms for a nice feature to have :)

**Comment by voischev** [comment]
correct configuration is up to user.

skip using plugins inside PostHTML can lead to unexpected output. Fall with an error-shows what is happening. imho

**Comment by vladshcherbin** [comment]
@voischev it's not related to correct configuration, it's an added opportunity (feature) to conditionally include plugins. You won't skip any plugins with this check because you want them to be functions in the first place as they are executed later (*A PostHTML plugin is a function* - from the docs).

I'm actually surprised to see such resistance to this small feature, you probably haven't used or needed similar thing before and can't fully understand how helpful and powerful it is. The last thing, I can show is a [sample rollup config](https://github.com/sveltejs/template/blob/master/rollup.config.js#L41-L45) where it's used.

Anyway, this is all I have to convince you. Hopefully you'll look at it from another, bright side, just for a second 😉🙏

**Comment by voischev** [comment]
rollup it's not the Holy Grail 😉

**Comment by vladshcherbin** [comment]
@voischev so why did you close this? any clear reason or downsides?
