### ISSUE TITLE
tree not walking into child nodes

### ISSUE THREAD

**Issue by lmcsu** [posthtml/posthtml#298]
Example:
```
posthtml()
    .use((tree) => {
        tree.walk((node) => {
            console.log('node', node);
        });
    })
    .process(html, { sync: true })
    .html;
```

Output:
```
node <!DOCTYPE html>
node 

node { tag: 'html',
  attrs: { lang: 'ru' },
  content:
   [ '\n',
     { tag: 'meta', attrs: [Object] },
     '\n',
     { tag: 'head', content: [Array] },
     '\n',
     { tag: 'body', content: [Array] },
     '\n\n' ] }
```
It's not walking into html tag, and the object of html tag has no "walk" method either.
I couldn't find anything about it in docs.

**Comment by Scrum** [comment]
@lmcsu Hi, Yes, more information is needed in the requirements documentation. We will fix it.

> It's not walking into html tag, and the object of html tag has no "walk" method either.
I couldn't find anything about it in docs.

because you are not returning the node.

it works for me
```js
posthtml()
    .use((tree) => {
        tree.walk((node) => {
            console.log('node', node);
            return node;
        });
    })
    .process(html, { sync: true })
    .html;
```

**Comment by lmcsu** [comment]
Thanks, it works with returning
