### ISSUE TITLE
"scoped" css polyfill

### ISSUE THREAD

**Issue by arestov** [posthtml/posthtml#30]
idea for posthtml plugin which implement css scoped attr like https://github.com/PM5544/scoped-polyfill, but  in "css module" style (https://github.com/css-modules/css-modules)

maybe already exists?

**Comment by voischev** [comment]
Good idea! :)

Write a small example of how you would like to see code on input and output?

**Comment by voischev** [comment]
@arestov ping

**Comment by arestov** [comment]
First implementation could be simple: do just scoping.

IN:
```html
<body>
  <style type="text/css" scoped>
    .nice {
      background: green;
      border: 1px solid white;
    }

    .complex-nice .nice {
      background: oldlace;
    }    
  </style>
  <div class="nice">
    Great!
  </div>
  <div class="complex-nice">
    <div class="nice">
      Super!
    </div>
  </div>
</body>
```

OUT:
```html

<body>
  <style type="text/css">
    .xDi-nice {
      background: green;
      border: 1px solid white;
    }

    .USo-complex-nice .xDi-nice {
      background: oldlace;
    }    
  </style>
  <div class="xDi-nice">
    Great!
  </div>
  <div class="USo-complex-nice">
    <div class="xDi-nice">
      Super!
    </div>
  </div>
</body>
```

Second implementation could target selecting speed for browser and collapse long selectors to one uniq classname

**Comment by voischev** [comment]
The challenge for posthtml looks simple enough.
You can make your own plugin https://github.com/posthtml/posthtml#create-posthtml-plugin?
I will help knowledge about PostHTML. Skype, fb, vk...?)
Let me know
