### ISSUE TITLE
Posthtml website for docs and other details

### ISSUE THREAD

**Issue by anikethsaha** [posthtml/posthtml#306]
update
---
The new posthtml website from [`posthtml.org`](https://github.com/posthtml/posthtml.org) is **live**

🎉 Preview at  https://posthtml-org.now.sh/#/
🔨 Made using @docsify
🚀 Deployed at Zeit

Original Issue
---

## I have created [posthtml website](https://posthtml-website.netlify.com/) using @docsifyjs .
Its an unofficial docs site.

**I am proposing if we can continue the development of this site in order to make it the official**

Its been developed in a private git repo. and would love to invite the collaborators of posthtml and others as well in order to have a look at the source code.

Lets discuss ⭐️

**Comment by Scrum** [comment]
@anikethsaha Hi, wow, this is very cool, I’m always happy for any suggestion, and we have a [repository](https://github.com/posthtml/posthtml.org) and a [domain](https://posthtml.org)

I am ready to provide you with everything you need to migrate to this domain, if that suits you

**Comment by anikethsaha** [comment]
@scrum I have invited you to the repo. You can take a look at the project.
I guess It needs the same code to be in your repo and the public path should be `docs` from the domain end. Thats it.

**Comment by Scrum** [comment]
@anikethsaha Accepted, give me time to migrate the previous project to the organization and I’ll figure out how to proceed. If you have soy considerations let me know. thanks

**Comment by anikethsaha** [comment]
> @anikethsaha Accepted, give me time to migrate the previous project to the organization and I’ll figure out how to proceed. If you have soy considerations let me know. thanks

perfect :+1:

**Comment by Scrum** [comment]
@anikethsaha you now have access to [posthtml.org](https://github.com/posthtml/posthtml.org)

**Comment by anikethsaha** [comment]
> @anikethsaha you now have access to [posthtml.org](https://github.com/posthtml/posthtml.org)

coool, I will do the changes 👍

**Comment by anikethsaha** [comment]
@Scrum can you DM me in [`twitter`](https://twitter.com/__ANIX__), your DM is closed thats why.
I got few things to clear up about zeit now !!
