### ISSUE TITLE
Dropping support for older NodeJs versions in a patch release breaks builds.

### ISSUE THREAD

**Issue by truh** [posthtml/posthtml#318]
> ✏️ Briefly describe the issue you are experiencing (or the feature you want to see added to the plugin). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://gitter.im/posthtml/posthtml

We use NodeJs version 8.10 for building our apps, the recent posthtml release broke our production builds.

### `Details`

> ✏️ Describe in more detail the problem you have been experiencing, if necessary.

`htmlnano` depends on `posthtml "^0.12.0"` which automatically updates to `0.12.2` without warning.

`parcel-bundler` depends on `htmlnano`, we are probably not the only people affected.

## `Error (Logs|Stacks)`

> 👉 Create a [gist](https://gist.github.com) which is a paste of your **full** logs, and link them here.

> ⚠️ Do **not** paste your full logs here (or at least hide them by using a `<details></details>` block), as it will make this issue long and hard to read! If you are reporting a bug, **always** include logs!

<details>

    warning parcel-bundler > htmlnano > uncss > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning parcel-bundler > htmlnano > uncss > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    warning parcel-bundler > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    warning parcel-bundler > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    [2/4] Fetching packages...
    error posthtml@0.12.2: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.10.0"
    error Found incompatible module.
    info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
    The command '/bin/sh -c yarn global add parcel-bundler' returned a non-zero code: 1

</details>

### `Reproduction (Code)`

Use parcel-bundler with Nodejs 8.

```dockerfile
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y add-apt-key curl
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg \
    | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" \
    | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn nginx git

RUN git clone https://github.com/parcel-bundler/examples.git

RUN yarn global add parcel-bundler
RUN cd examples/react; yarn build
```

### `Environment`

> ℹ️ Please provide information about your current environment.

|OS|node|npm/yarn|package|
|:Ubuntu:|:8.10:|:yarn 1.22.1:|:parcel-bundler:|
|[name][version]|[version]|[version]|[version]|

**Comment by Scrum** [comment]
@truh fixed in posthtml@0.12.3
