### ISSUE TITLE
how to save existen formatting?

### ISSUE THREAD

**Issue by arestov** [posthtml/posthtml#32]
Current implementation removed spaces (wich is not expected).
Is it possible to save existen formatting (spaces, etc)? maybe some option?

**Comment by voischev** [comment]
it is bug fixed in https://github.com/posthtml/posthtml/commit/42b4d156a1b39bf6e590ba222d1e79969af7095a 

wait for a new version... 10 min)

**Comment by voischev** [comment]
@arestov update to 0.0.4

**Comment by arestov** [comment]
cool, thank you! :+1:  waiting for npm update :)
