### ISSUE TITLE
TypeScript bindings don't work as expected

### ISSUE THREAD

**Issue by CodingDoug** [posthtml/posthtml#324]
When importing a module using TS, it's expected to be able to write a line like this:

```
import * as posthtml from 'posthtml'
posthtml(...)
```

This would get the exports from the module into a single identifier.  However, since the default export is a function, it actually doesn't work at all.  You get the following error message:

> TypeError: posthtml_1.default is not a function

There is no easy workaround for this, given the current type bindings.  It's generally suggested to [avoid using default exports](https://basarat.gitbook.io/typescript/main-1/defaultisbad).

express handles this pretty well.  You can see its TS bindings [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts).

A similar fix for posthtml would involve making its binding look more like this:

```
declare namespace posthtml { ... }

declare function posthtml<TThis, TMessage>(
  plugins?: posthtml.Plugin<TThis>[]
): posthtml.PostHTML<TThis, TMessage>;

export = posthtml
```

There might be a better way, but this worked for me.  I am able to use my example import code from above this way.  TS is very important for my project, and having proper bindings will go a long way.

**Comment by mrmlnc** [comment]
Hello, @CodingDoug,

Thanks for the detailed information for the issue.

You're right. The current typings are written incorrectly — we must use `export = xxx`.
