### ISSUE TITLE
Please consider to make a postcss-htmlhint plugin

### ISSUE THREAD

**Issue by d892fc** [posthtml/posthtml#351]
After a lot of googling, I found out that PostHTML the best candidate to become the platform for HTML build tools, like rollup.js or webpack for JavaScript, or PostCSS for CSS.

Please consider add posthtnl-htmllint, posthtml-htmlhint, posthtml-ejs, poshtml-html-minifier plugins for PostHTML, because they are most popular build tools of HTML.

**Comment by Scrum** [comment]
> After a lot of googling, I found out that PostHTML the best candidate to become the platform for HTML build tools, like rollup.js or webpack for JavaScript, or PostCSS for CSS.
> 
> Please consider add posthtnl-htmllint, posthtml-htmlhint, posthtml-ejs, poshtml-html-minifier plugins for PostHTML, because they are most popular build tools of HTML.

Hello, you can add these plugins to the list of plugins or we can transfer these plugins to the general posthtml repository, for this we need the creator's rights or you can transfer to me and I will already transfer them to the general repository

**Comment by d892fc** [comment]
Thank you for your reply!

These plugins do not exist at this moment , and I am not sure if I can make them, because I don't write JavaScript code very much.

I'm happy to do this becsuse it's open source activity.  I will let you know if I have some progress.


-------- 原始邮件 --------
发件人： Ivan Demidov ***@***.***>
日期： 2021年3月30日周二 14:08
收件人： posthtml/posthtml ***@***.***>
抄送： d892fc ***@***.***>, Author ***@***.***>
主 题： Re: [posthtml/posthtml] Please consider to make a postcss-htmlhint plugin (#351)

After a lot of googling, I found out that PostHTML the best candidate to become the platform for HTML build tools, like rollup.js or webpack for JavaScript, or PostCSS for CSS.

Please consider add posthtnl-htmllint, posthtml-htmlhint, posthtml-ejs, poshtml-html-minifier plugins for PostHTML, because they are most popular build tools of HTML.

Hello, you can add these plugins to the list of plugins or we can transfer these plugins to the general posthtml repository, for this we need the creator's rights or you can transfer to me and I will already transfer them to the general repository

―
