### ISSUE TITLE
TOC content without possibility to scroll

### ISSUE THREAD

**Issue by maziac** [posthtml/posthtml#371]
Hi,
Im not sure if this is a feature request, if this is an error or if I'm just missing some thing.

The situation is that I have a quite large table of contents and I would like to give the user the ability to scroll inside the TOC.
Is there an option for it? Or how could I achieve it?

**Comment by voischev** [comment]
👋 Hi. To do this, you need to create styles for the toc element id

Like
```css
#toc {
height: 100px;
overflow: scroll;
}
```

doc https://github.com/posthtml/posthtml-toc

**Comment by maziac** [comment]
Thanks.
Works like a charm.
