### ISSUE TITLE
Match comments

### ISSUE THREAD

**Issue by admdh** [posthtml/posthtml#56]
Is there any good way to match comments?

**Comment by zxqfox** [comment]
:+1:

**Comment by voischev** [comment]
I like it more
`.match(RegExp, fn)` 

Now you can do
```js
.walk(function(node) {
    if(typeof node === 'string') { 
        // do somsing ;)
    }
})
```

**Comment by voischev** [comment]
@admdh ping. Me upb example

**Comment by voischev** [comment]
#57

**Comment by admdh** [comment]
i would like to get comment's and based on it's value generate another file. for example:
```html
<!-- element-name="DOCUMENT" -->
```
will compile to
```
<element name="DOCUMENT">
</element>
```

**Comment by admdh** [comment]
it would be great to use possibilities of htmlparser2 comment handling example from http://demos.forbeslindesay.co.uk/htmlparser2/
```json
{
data: ' element-name="DOCUMENT" '
type: 'comment'
next: {+}
prev: {+}
parent: {+}
}
```
so there was possibility to match on comment something like with matchClass but matchComment see example below
```
tree.matchComment( ... , function(node) {
   return node.content
    return ''; // delete this node in tree
});
```

**Comment by voischev** [comment]
@admdh 
I understand what they mean.
But matchClass method harder than working with comments. 
Comments in PostHTML are strings and need to work with them as a string.
Later, things can change

htmlparser2 likely to be replaced by own parser. And we can not be tied to it

Now API a simple, I want keep this. Especially if the problem can be resolved in a few lines of code

I suggest to solve the problem so

```js
tree.walk(function(node) {
    if(typeof node === 'string' && /<!--/g.test(node)) { 
        var data = node.slice('=');
        return { tag: data[0].replace('-name', '').trim(), attrs { name: data[1].replace('"', '').trim() };
    }
    return node;
}
```

**Comment by voischev** [comment]
@admdh 
if resolve issue #57 be it
```js
tree.match(/<!--/g, function(node) {
    var data = node.slice('=');
    return { tag: data[0].replace('-name', '').trim(), attrs { name: data[1].replace('"', '').trim() }};
})
```
looks good!? ))

**Comment by admdh** [comment]
Yes, Thank you this will be good!
