### ISSUE TITLE
processSync helper

### ISSUE THREAD

**Issue by zxqfox** [posthtml/posthtml#67]
to call `process(..., {sync: true})`

**Comment by TrySound** [comment]
@zxqfox Async plugins can't work in sync mode. So, why?

**Comment by zxqfox** [comment]
Good question.

1. Because we can do it;
2. This is a tiny addition that don't change anything;
3. Sync suffix is a common method for marking sync functions in node env.

So why not? It's not a big deal at my pov.

**Comment by TrySound** [comment]
@zxqfox This is a tiny addition that haven't any sence. And `Because we can do it` is not the reason for something.

**Comment by voischev** [comment]
@TrySound Why not? Now sync options look like a hack.

```js
posthtml().process(html).then(result => result.html)
let = posthtml().process(html, { sync: true }).html
```
justly yet, without spoofing context
```
posthtml().process(html).then(result => result.html)
let = posthtml().processSync(html).html
```
