### ISSUE TITLE
Grunt postHTML?

### ISSUE THREAD

**Issue by TCotton** [posthtml/posthtml#70]
Hey team,
I've already contributed to the postCSS ecosystem (https://www.npmjs.com/package/postcss-mq-keyframes), and I just wondered what you thought about me creating a module that adds posthtml support to Grunt?

**Comment by voischev** [comment]
You want create grunt-posthtml plugin? Do it! :)

**Comment by TCotton** [comment]
Great! I'm working on it now (https://github.com/TCotton/grunt-posthtml). I'll ask you to do a code review when I'm ready :)

**Comment by voischev** [comment]
@TCotton ok. Wait you

**Comment by voischev** [comment]
@TCotton ping :)

**Comment by TCotton** [comment]
I spent Friday and Saturday on it. Looking other code as well, like Grunt postCSS, to see how they have implemented it. Give me a few days and I'll come back to it again

**Comment by TCotton** [comment]
Hey,

Rather than jump straight into the Grunt Plugin I'd thought I woud create my own custom PostHTML plugin first so that I can become familiar with the script: https://github.com/TCotton/posthtml-head-elements

The idea is the HTML head elements - script, link, meta etc - can be placed into a separate JSON file and inserted where a custom tag (```<posthtml-head-elements></posthtml-head-elements>```) is placed during the build process.

My first approach was to build the PostHTMLTree from the JSON file (https://github.com/TCotton/posthtml-head-elements/blob/master/index.js), but I had difficulty inserting the PostHTMLTree into the right node.

My second idea, was to use posthtml-render and create a string but I don't think this will work. 

I see that there is a .parse() "Arguments: {String} html Parses HTML string into a PostHTMLTree object.", but I'm presuming this is the chain of functions that comes after posthtml() in the settings

**Comment by voischev** [comment]
@TCotton Hi! Look at this PR https://github.com/TCotton/posthtml-head-elements/pull/1

**Comment by TCotton** [comment]
Okay, done with posthtml-head-elements: https://github.com/TCotton/posthtml-head-elements

If you could do a code review for me Ivan, I'm going to go back to the Grunt PostHTML plugin

**Comment by voischev** [comment]
@TCotton code review https://github.com/TCotton/posthtml-head-elements/pull/2

**Comment by TCotton** [comment]
I'm doing some more work on the Grunt plugin. I aim to have something ready for code review by the end of the week

**Comment by voischev** [comment]
thanks you! :+1:

**Comment by TCotton** [comment]
Here you go Ivan do you want to give it a spin: https://github.com/TCotton/grunt-posthtml

It's just a wrapper for PostHTML so all features should be the same. If you can take a look at the code and make sure all features are such a [options](https://github.com/posthtml/posthtml#options) work as intended

**Comment by island205** [comment]
:+1:

**Comment by voischev** [comment]
@TCotton ок! You can write about this in Readme? After that it will be possible to close this issue

**Comment by voischev** [comment]
@TCotton This package will be in NPM?

**Comment by TCotton** [comment]
Of course, I'll upload it now to npm and then immediately try it out on my own portfolio which still uses Grunt

**Comment by voischev** [comment]
I'm waiting for feedback ;)

**Comment by TCotton** [comment]
okay, I've uploaded it to npm.com and integrated it my portfolio build process.
I'm happy with it :) I think we can close this issue now.
I'll put in a pull request for the PostHTML README.md file

**Comment by voischev** [comment]
@TCotton thanks you! :+1:
