### ISSUE TITLE
New plugin: posthtml-transformer

### ISSUE THREAD

**Issue by flashlizi** [posthtml/posthtml#78]
posthtml-transfomer process HTML by directives in node attrs, such as inline scripts and styles, remove useless tags, concat scripts and styles etc.

github: https://github.com/flashlizi/posthtml-transformer
npm: https://www.npmjs.com/package/posthtml-transformer

**Comment by voischev** [comment]
Cool! You should write about it in [plugins](https://github.com/posthtml/posthtml#plugins) section
