### ISSUE TITLE
Plugin idea: currency

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml#83]
Hi!
I think would be cool to replace somehow unsupported (yet) (in older OS/browsers) currency glyphs with some fallback.
For example:
₽ – Russian ruble
Can be replaced to `<span class="ruble">c</span>` to use “ALS Rubl” font where letters are following style of some other fonts, `c` is for Arial Bold.
Can be replaced to `<span class="ruble-arial-bold">руб.</span>` to use pseudo-element with `content: "c";`.
Or I have just to use basic text replacement?

**Comment by voischev** [comment]
Not bad idea for plugin. 

How this solve your problem? Write more examples for uses

Some solutions to these can be plugin-wrappers [posthtml-retext](https://github.com/voischev/posthtml-retext) or [posthtml-textr](https://github.com/voischev/posthtml-textr)
But they do not work with DOM. `<span class="ruble">c</span>` => ₽ ;)

**Comment by Grawl** [comment]
I don't know yet how I want it to be but I think PostHTML is to solve problems like this.

We need:

1. Display native glyph if available
1. Fallback to custom font if glyph is not unavailable
1. Fallback to `руб.` if custom font is not loaded

What we can?

**Comment by voischev** [comment]
1. in browser? Parser must to work in client browser. [posthtml-render](https://github.com/posthtml/posthtml-render) ([PostHTMLTree](https://github.com/posthtml/posthtml#tree-in-posthtml-posthtmltree) render to html in client) work in browser or browserify PostHTML. 

we can all basically :)

**Comment by Grawl** [comment]
I want to add ruble sign into my source code and add fallback with PostHTML.

I think other that replacing is an CSS&HTML-only issue.

So I need just replace ruble sign with something smart. Want to help?

**Comment by voischev** [comment]
in ES6 example
```js

// PostHTML plugin
export function repaceRuble(tree) {
    
    tree.match(/₽/gi, node => ({ // find string with the ruble, return new content obj
        tag: false,
        content: Array.prototype.concat.call([], node.split('₽').map(test => ([ text, { tag: 'span', attrs: { class: 'ruble' }, content: ['c'] }]))))
    });
}
```

VS basic replace

```js
// simple function
import { readFileSync } from 'fs';

export function repaceRuble(pathToFile) {
    readFileSync(pathToFile).toString().replace(/₽/gi, '<span class="ruble">c</span>');
}
```

**Comment by voischev** [comment]
more replace back example) 
```html
text 
<span class="ruble">c</span>
<span class="ruble">RUB.</span>
<DIV class="ruble">c</DIV>
```
```js
tree.match({ attrs: { class: 'ruble' }}, node => ('₽'));
```
output:
```html
text 
₽
₽
₽
```

**Comment by Gurylev** [comment]
Влезу по-русски. У меня никакой английский, простите.

Мне требуется в рабочем проекте заменять ₽ на span в браузерах, где символ не поддерживается. Как в примере из [комментария про ES6](https://github.com/posthtml/posthtml/issues/83#issuecomment-161911650) выше. Я не знаю, правда, что именно проверять необходимость замены.

А ещё мне кажется странным это делать при компиляции. Мне кажется, это должно происходить на фронтенде. Проверка и замена во время onload документа на span в случае поломанного символа. Или всё таки это можно определить на бэке?

Однако, на бэкэнде я бы (если б умел и имел достаточно времени) решал ещё одну задачу, связанную с валютами. Во всех языках правильно писать бакс слева от ценника, а не справа. $500, а не 500$. В арабском правильно справа, но direction: rtl замечательно поворачивает текст, заменять дополнительно не требуется. Переводчики всё время пишут с ошибками, я устал им повторять, что так неправильно и исправлять за ними. Хотелось бы разрешать эту проблему автоматически. Или хотя бы на уровне lint'а. Это возможно?

**Comment by Grawl** [comment]
Ладно, раз уж пока что решаем задачу нашей валюты, давай по-русски. Так действительно удобней (язык-то богаче, ке-ке).

Знак рубля – это часть Unicode, появился в определённой версии. Можно ли определить поддержку версии Unicode через JS? С ходу удалось найти следующее:

[Modernizr Unicode character detection plugin](https://gist.github.com/ZeeAgency/1437455) – проверка на ширину символа, так как вместо отсутствующего символа Unicode печатает квадрат
[Parsing emoji Unicode in JavaScript](http://crocodillon.com/blog/parsing-emoji-unicode-in-javascript) – какая-то весьма хитрая проверка на поддержку Emoji через `canvas`.

А в остальном нам надо будет лишь заменить `₽` на `<span class='ruble'>руб.</span>`, прятать “руб.” стилями и заменять на знак рубля через `.ruble::before { content: 'c' }`. Но стили уже в проекте, я думаю, надо делать.

---

Что насчёт положения валюты относительно числа, я думаю, можно как-то парсить и переставлять их.

**Comment by Grawl** [comment]
Подумав немного, добавлю: если во время компиляции менять – то можно любую валюту на конструкции вроде `<span class='ruble'>руб.</span>` или `<span class='dollar'>USD</span>`, чтобы можно было их стилизовать, например. Или опираться на них, м? Давайте так сделаем. И настройки будут какими-нибудь такими:

```js
{
cultureType: local,
classType: stock,
classPrefix: 'currency-'
}
```

…где `cultureType` отвечает за использование одного из двух наборов замен, как то:

`cultureType: local`: название на местном языке – `'руб.'`, `'dollar'`, `'peso'`, `'төгрөг'`, …
`cultureType: international`: название по-английски – `'ruble'`, `'dollar'`, `'tugrik'`, … 
*(лучше сокращённо, но я не знаю, как сократить что-либо кроме рубля)*
`cultureType: stock`: код валюты – `'RUR'`, `'USD'`, `'MNT'`, …

А `classType` – то, что добавлять к классу: `'ruble'` или `'RUR'`, например (может пригодиться при использовании библиотеки с изображениями, именованными по кодам валют)

**Comment by voischev** [comment]
Как можно работать с браузером я выше писал.
Но напишите сначала хотя бы для сервера. 
Всегда можно делать следующее — первый раз рендерим фолбеки, какой нибудь простенький скриптик на клиенте чекает возможность указывать валюту в юникоде, ложет в куку и потом уже все последующие запросы просто рендерим юникодами. 

Клиент нагружать как то не хочется. Ну и PostHTML как бы генерит строку, что не очень хорошо в браузере, если только у вас не SPA там можно как то с этим жить. 

А так, для браузеров было бы круто написать плагин __PostHTML-DOM__ — который вместо строк генерил бы сразу DOM! Тогда было бы все сильно быстрее. Но опять же — зависит от задач.

**Comment by Grawl** [comment]
Да мне бы просто ₽ в исходники писать, в принципе…

**Comment by voischev** [comment]
@Grawl Так пиши :) кто тебе мешает? Или есть какие то требования? Я на маке... может по этому не вижу проблем.

**Comment by Grawl** [comment]
Да я тоже на маке, но хочу fallback замутить. Простенький.

**Comment by Gurylev** [comment]
Я тут новый проект пилю. Выбирал плагины для него. И наткнулся на https://github.com/talgautb/postcss-currency
Так что, думаю, эту ишью можно закрывать.

**Comment by voischev** [comment]
Ну так он про css.
Нужно же что-то и с html поделать.

**Comment by Grawl** [comment]
Он ещё и почти наоборот работает по сравнению с моей идеей.

**Comment by talgautb** [comment]
А разве не проще тянуть для валют маааааленький шрифт ? :) и реализовать через `css`

**Comment by Grawl** [comment]
@talgautb ну как бы **даа**, я о чём и говорю

- в исходниках использовать `₽`

  ```html
  <p>1200₽</p>
  ```
- компилировать его в какой-нибудь `<span class="ruble">руб.</span>`

  ```html
  <p>1200<span class="ruble"> руб.</span></p>
  ```

- с помощью CSS прятать “руб.”

  ```css
  .ruble {
    font-size: 0;
  }
  ```
- и, допустим, псевдоэлементом отображать нужный глиф

  ```css
  .ruble::before {
    content: 'a';
    font-size: initial;
    font-family: "ALS Rubl";
  }
  ```

  Также можно делать это через SVG, например, или PNG – либо все техники встраиваются в библиотеку, либо библиотека отвечает только за замену символов валют на нужные элементы, как я описывал в таблице выше.

**Comment by talgautb** [comment]
@Grawl `почти наоборот работает по сравнению с моей идеей`
как раз он работает так как надо :)
просто усовершенствовать в html можно, но это лишнее, так как шрифт поддерживают браузеры даже древние

**Comment by Grawl** [comment]
Я не понимаю, как ты не понимаешь.

**Comment by talgautb** [comment]
@Grawl ок, расходимся :)

**Comment by voischev** [comment]
Закрываем ищью?

**Comment by Grawl** [comment]
Может, всё-таки напишем расширение-библиотеку?

**Comment by voischev** [comment]
Решите кто будет делать, я помогу чем могу

**Comment by Grawl** [comment]
Ну я вряд ли сделаю это хорошо, нет опыта (и времени – меняю работу).
