### ISSUE TITLE
Plugin idea: add type="button" to buttons without a type

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml#84]
I want to specify a `type` for a `<button>` only if I want to make it `submit` but basically I won't submit bu any default button.

This plugin may be like “default attributes for elements”.

**Comment by voischev** [comment]
You can do it! ;)

Example:
```
tree => {
    tree.match({ tag: 'button' }, node => {
        node.attrs? (node.attrs.type = node.attrs.type || 'button') : (node.attrs = { type: 'button' })
        return node;  
    })
}
```
etc.

**Comment by awinogradov** [comment]
@Grawl ping. What status?

**Comment by Grawl** [comment]
I do nothing.
