### ISSUE TITLE
Plugn idea:css module

### ISSUE THREAD

**Issue by zhouwenbin** [posthtml/posthtml#85]
https://github.com/css-modules/css-modules
https://github.com/outpunk/postcss-modules

read the `module.json`file，and replace the html classes.

**Comment by voischev** [comment]
:+1: Very good idea!

**Comment by c01nd01r** [comment]
+ posthtml-modular-css

**Comment by zhouwenbin** [comment]
no the same

**Comment by outpunk** [comment]
Going to do this soon, guys.

**Comment by maltsev** [comment]
Done: [posthtml-css-modules](https://www.npmjs.com/package/posthtml-css-modules)

**Comment by voischev** [comment]
@zhouwenbin closed issue?

**Comment by awinogradov** [comment]
@voischev close

**Comment by zhouwenbin** [comment]
@maltsev good job

**Comment by maltsev** [comment]
@zhouwenbin thanks!
