### ISSUE TITLE
Chat room?

### ISSUE THREAD

**Issue by jonathantneal** [posthtml/posthtml#87]
Where do I go to discuss plugin ideas with other people in the PostHTML community? Could there be https://gitter.im/posthtml/posthtml ?

**Comment by voischev** [comment]
@awinogradov create room ;)

**Comment by jonathantneal** [comment]
@voischev, are you able to create one?

**Comment by awinogradov** [comment]
@jonathantneal [![Gitter](https://badges.gitter.im/posthtml/posthtml.svg)](https://gitter.im/posthtml/posthtml?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)
