### ISSUE TITLE
Plugin boilerplate

### ISSUE THREAD

**Issue by jonathantneal** [posthtml/posthtml#88]
Should this project recommend a scaffolding tool as PostCSS does? Do you think this would be helpful to new plugin authors?

https://github.com/jonathantneal/posthtml-plugin-boilerplate

**Comment by voischev** [comment]
Good idea! :+1: :+1: :+1: 

You should write about this [helpers](https://github.com/posthtml/posthtml#helpers) section

**Comment by awinogradov** [comment]
:+1:

**Comment by voischev** [comment]
@jonathantneal thx for boilerplate! :)
