### ISSUE TITLE
Plugin repository 

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml#93]
Will be cool to create a thing similar to postcss.parts

**Comment by voischev** [comment]
Maybe you create this? :)

**Comment by Grawl** [comment]
Just cannot. Have no experience in web app coding.

**Comment by maltsev** [comment]
Here you are: http://maltsev.github.io/posthtml-plugins/

**Comment by Grawl** [comment]
Awesome!

**Comment by voischev** [comment]
@maltsev write about in Readme ;)
Create PR
