### ISSUE TITLE
walk() and match() as a separate module

### ISSUE THREAD

**Issue by maltsev** [posthtml/posthtml#94]
Sometimes I need to find a node in a tree, which hasn't `walk()` and `match()` functions (subtree, for example). What do you think, if we decouple these functions in a separate module (like `posthtml-parser` and `posthtml-render`)? So they can be used everywhere, with all kinds of PostHTML-trees.

**Comment by voischev** [comment]
```js 
var match = requare('posthtml/lib/api').match;
var walk = requare('posthtml/lib/api').walk;
```
or in plugins
```js
var match = tree.match;
match.apply(node, { tag: 'test' }, function(node) { return node; }); 
```

parser & render again later become part of the PostHTML package

**Comment by maltsev** [comment]
@voischev thank you for the advice! I'll try this approach.

**Comment by maltsev** [comment]
Unfortunately, it won't work. `match` depends on `node.walk`, which is `undefined`. So we've to define it first:
```js
var match = requare('posthtml/lib/api').match;
var walk = requare('posthtml/lib/api').walk;

node.walk = function () {
    return walk.apply(node, arguments);
};
match.apply(node, [{ tag: 'test' }, function(node) { return node; }]); 
```

Should we fix it (incapsulate in `api.js`)?

**Comment by voischev** [comment]
@maltsev look at https://github.com/posthtml/posthtml/pull/97/files

**Comment by voischev** [comment]
@maltsev use v0.8.1

**Comment by maltsev** [comment]
Thank you!
