### ISSUE TITLE
Error: custom single tags

### ISSUE THREAD

**Issue by maltsev** [posthtml/posthtml#95]
PostHTML doesn't support custom single tags. Here is the failed test: https://github.com/maltsev/posthtml/commit/42247ac196eab736aea8acb2a03a5b0c7541e377

`<custom><custom>` is parsed to `[{tag: 'custom', content: [{tag: 'custom'}]}]` and not to 
`[{tag: 'custom'}, {tag: 'custom'}]`.

I guess the [posthtml-parser](https://github.com/posthtml/posthtml-parser/) should be extended to fix this error.

**Comment by maltsev** [comment]
I submitted the issue in the `htmlparser2` repository: [custom void elements](https://github.com/fb55/htmlparser2/issues/164)

**Comment by awinogradov** [comment]
We can solve it in the future by custom parser. Now it's not about posthtml. @maltsev thanks! Looking forward)
